//! Enum types for TUI state management.

use super::*;

#[derive(Debug, Clone, PartialEq)]
pub enum TuiMode {
    Chat,
    Overlay,
    Select,
    Permission,
    CommandPalette,
    DiffViewer,
    SessionTree,
    Onboarding,
}

#[derive(Debug, Clone)]
pub enum Msg {
    Submit,
    TextareaKey(KeyEvent),
    InsertNewline,
    Quit,
    ToggleSidebar,
    OpenCommandPalette,
    CloseModal,
    ConfirmModal,
    ScrollUp,
    ScrollDown,
    ScrollPageUp,
    ScrollPageDown,
    PermissionConfirm,
    PermissionCancel,
    PermissionAlways,
    PermissionSkip,
    CommandPaletteFilter(char),
    CommandPaletteBackspace,
    CommandPaletteUp,
    CommandPaletteDown,
    CommandPaletteConfirm,
    CommandPaletteCancelArgument,
    AgentEvent(AgentEvent),
    Tick,
    CursorBlink,
    SlashCommand(runie_core::slash_command::SlashCommand),
    ToggleSessionTree,
    SessionTreeUp,
    SessionTreeDown,
    SessionTreeConfirm,
    OnboardingNext,
    OnboardingBack,
    OnboardingNavigateUp,
    OnboardingNavigateDown,
    OnboardingSelectProvider(usize),
    OnboardingSelectModel(usize),
    OnboardingKeyInput(char),
    OnboardingKeyBackspace,
    OnboardingSearchInput(char),
    OnboardingSearchBackspace,
    OnboardingSubmit,
    OnboardingSkip,
    PermissionTimeout,
    SelectUp,
    SelectDown,
    SelectConfirm,
    SelectToggleDetails,
    ClearInput,
    ClearInputConfirm,
    ClearChat,
    DirectCommand(PaletteCommand),
    Paste(String),
    ModelsFetched(Vec<ModelInfo>),
    ModelsFetchFailed(String),
    Resize(u16, u16),
    Stop,
    SwitchModel,
    SetGitInfo { repo: String, branch: String, path: String },
    SetTopBarMockChecks {
        checks_passed: Option<usize>,
        checks_total: Option<usize>,
        percentage: Option<f32>,
        context_badges: Vec<String>,
    },
    SetTopBarRealChecks { context_badges: Vec<String> },
    SetInputRightInfo(String),
    EnterOnboarding,
    SetCurrentModel(Option<String>),
    SetMockMode(bool),
    ResetAgentState,
    UpdateTopBarContext { model: String, context_window: Option<usize>, estimated_tokens: Option<usize> },
    HistoryUp,
    HistoryDown,
    CopyLastResponse,
}

impl PartialEq for Msg {
    fn eq(&self, other: &Self) -> bool {
        use Msg::*;
        match (self, other) {
            (Submit, Submit) => true,
            (TextareaKey(a), TextareaKey(b)) => a == b,
            (InsertNewline, InsertNewline) => true,
            (Quit, Quit) => true,
            (ToggleSidebar, ToggleSidebar) => true,
            (OpenCommandPalette, OpenCommandPalette) => true,
            (CloseModal, CloseModal) => true,
            (ConfirmModal, ConfirmModal) => true,
            (ScrollUp, ScrollUp) => true,
            (ScrollDown, ScrollDown) => true,
            (ScrollPageUp, ScrollPageUp) => true,
            (ScrollPageDown, ScrollPageDown) => true,
            (PermissionConfirm, PermissionConfirm) => true,
            (PermissionCancel, PermissionCancel) => true,
            (PermissionAlways, PermissionAlways) => true,
            (PermissionSkip, PermissionSkip) => true,
            (CommandPaletteFilter(a), CommandPaletteFilter(b)) => a == b,
            (CommandPaletteBackspace, CommandPaletteBackspace) => true,
            (CommandPaletteUp, CommandPaletteUp) => true,
            (CommandPaletteDown, CommandPaletteDown) => true,
            (CommandPaletteConfirm, CommandPaletteConfirm) => true,
            (CommandPaletteCancelArgument, CommandPaletteCancelArgument) => true,
            (AgentEvent(_), AgentEvent(_)) => true,
            (Tick, Tick) => true,
            (CursorBlink, CursorBlink) => true,
            (SlashCommand(_), SlashCommand(_)) => true,
            (ToggleSessionTree, ToggleSessionTree) => true,
            (SessionTreeUp, SessionTreeUp) => true,
            (SessionTreeDown, SessionTreeDown) => true,
            (SessionTreeConfirm, SessionTreeConfirm) => true,
            (OnboardingNext, OnboardingNext) => true,
            (OnboardingBack, OnboardingBack) => true,
            (OnboardingNavigateUp, OnboardingNavigateUp) => true,
            (OnboardingNavigateDown, OnboardingNavigateDown) => true,
            (OnboardingSelectProvider(a), OnboardingSelectProvider(b)) => a == b,
            (OnboardingSelectModel(a), OnboardingSelectModel(b)) => a == b,
            (OnboardingKeyInput(a), OnboardingKeyInput(b)) => a == b,
            (OnboardingKeyBackspace, OnboardingKeyBackspace) => true,
            (OnboardingSearchInput(a), OnboardingSearchInput(b)) => a == b,
            (OnboardingSearchBackspace, OnboardingSearchBackspace) => true,
            (OnboardingSubmit, OnboardingSubmit) => true,
            (OnboardingSkip, OnboardingSkip) => true,
            (ClearInput, ClearInput) => true,
            (ClearInputConfirm, ClearInputConfirm) => true,
            (ClearChat, ClearChat) => true,
            (DirectCommand(a), DirectCommand(b)) => a == b,
            (Paste(a), Paste(b)) => a == b,
            (ModelsFetched(a), ModelsFetched(b)) => a == b,
            (ModelsFetchFailed(a), ModelsFetchFailed(b)) => a == b,
            (Resize(a_w, a_h), Resize(b_w, b_h)) => a_w == b_w && a_h == b_h,
            (Stop, Stop) => true,
            (PermissionTimeout, PermissionTimeout) => true,
            (SelectUp, SelectUp) => true,
            (SelectDown, SelectDown) => true,
            (SelectConfirm, SelectConfirm) => true,
            (SelectToggleDetails, SelectToggleDetails) => true,
            (SwitchModel, SwitchModel) => true,
            (SetGitInfo { .. }, SetGitInfo { .. }) => true,
            (SetTopBarMockChecks { .. }, SetTopBarMockChecks { .. }) => true,
            (SetTopBarRealChecks { .. }, SetTopBarRealChecks { .. }) => true,
            (SetInputRightInfo(a), SetInputRightInfo(b)) => a == b,
            (EnterOnboarding, EnterOnboarding) => true,
            (SetCurrentModel(a), SetCurrentModel(b)) => a == b,
            (SetMockMode(a), SetMockMode(b)) => a == b,
            (ResetAgentState, ResetAgentState) => true,
            (UpdateTopBarContext { .. }, UpdateTopBarContext { .. }) => true,
            (HistoryUp, HistoryUp) => true,
            (HistoryDown, HistoryDown) => true,
            (CopyLastResponse, CopyLastResponse) => true,
            _ => false,
        }
    }
}

// ─── Cmd ────────────────────────────────────────────────────────────────────────

#[derive(Debug, Clone)]
pub enum Cmd {
    SpawnAgent { messages: Vec<AgentMessage> },
    SendPermission { decision: PermissionDecision },
    SlashCommand(SlashCommand),
    SaveSettings { provider: String, model: String, api_key: String },
    FetchModels { provider_id: String, api_key: String },
    Rollback { tool_call_id: String },
    Interrupt,
}

impl PartialEq for Cmd {
    fn eq(&self, other: &Self) -> bool {
        use Cmd::*;
        match (self, other) {
            (SpawnAgent { .. }, SpawnAgent { .. }) => true,
            (SendPermission { decision: a }, SendPermission { decision: b }) => a == b,
            (SlashCommand(_), SlashCommand(_)) => true,
            (SaveSettings { provider: a, model: b, api_key: c }, SaveSettings { provider: d, model: e, api_key: f }) => a == d && b == e && c == f,
            (FetchModels { provider_id: a, api_key: b }, FetchModels { provider_id: c, api_key: d }) => a == c && b == d,
            (Rollback { tool_call_id: a }, Rollback { tool_call_id: b }) => a == b,
            (Interrupt, Interrupt) => true,
            _ => false,
        }
    }
}

#[derive(Debug, Clone, PartialEq)]
pub enum TuiAction {
    Quit,
    Submit(String),
    Command(String),
    Cancel,
    ToolPermission { tool: String, action: PermissionAction },
}
