//! Config validation against the schemars-generated JSON schema using `jsonschema`.
//!
//! Replaces the hand-written validator with `jsonschema` to stay in sync with
//! the schema generated by `schemars` automatically.

use serde_json::Value;

use crate::config::schema::schema_value;

fn format_json_pointer(path: &[String]) -> String {
    if path.is_empty() {
        String::new()
    } else {
        format!("/{}", path.join("/"))
    }
}

fn check_unknown_fields(value: &Value, errors: &mut Vec<String>) {
    let Some(obj) = value.as_object() else { return };
    let schema = schema_value();
    let Some(schema_props) = schema
        .get("properties")
        .and_then(|p| p.as_object())
        .map(|o| o.keys().collect::<std::collections::HashSet<_>>())
    else {
        return;
    };
    for key in obj.keys() {
        if !schema_props.contains(key) {
            errors.push(format!("{key}: unknown field (ignored)"));
        }
    }
}

/// Validate a JSON value against the schemars-generated config JSON schema.
///
/// Returns a list of error messages.
pub fn validate(value: &Value) -> Vec<String> {
    let schema = schema_value();
    let Ok(compiled) = jsonschema::JSONSchema::compile(&schema) else {
        return vec!["failed to compile schema".into()];
    };

    let js_errors: Vec<String> = compiled
        .validate(value)
        .err()
        .into_iter()
        .flatten()
        .map(|e| {
            let path = format_json_pointer(&e.instance_path);
            if path.is_empty() {
                e.to_string()
            } else {
                format!("{path}: {e}")
            }
        })
        .collect();

    let mut errors = js_errors;
    check_unknown_fields(value, &mut errors);
    errors
}
