//! # App Library
//!
//! Hot-reloadable application logic.
//! Generated by rune - DO NOT EDIT

mod native;

use protocol::{App, AppState};

/// Create a new app instance.
#[no_mangle]
pub extern "C" fn create_app() -> *mut dyn App {
    Box::into_raw(Box::new(AppImpl::default()))
}

#[derive(Default)]
struct AppImpl;

impl App for AppImpl {
    fn update(&mut self, _state: &mut AppState) {
        // Generated code will be inserted here by rune compiler
    }

    fn render(&self, _f: &mut ratatui::Frame<'_>, _state: &AppState) {
        // Generated code will be inserted here by rune compiler
    }

    fn handle_key(&mut self, _key: crossterm::event::KeyEvent, _state: &mut AppState) {}
}
