//! App library - hot-reloadable app logic.
//!
//! ~15 lines of hand-written wiring. Logic is in .r.ts files.

#![allow(improper_ctypes_definitions)]

mod native;

use protocol::{App, AppState};

/// Create new app instance - called by host binary.
#[no_mangle]
pub extern "C" fn create_app() -> *mut dyn App {
    Box::into_raw(Box::new(AppImpl::default()))
}

#[derive(Default)]
struct AppImpl;

impl App for AppImpl {
    fn update(&mut self, _state: &mut AppState) {
        // Will be generated by rune
    }

    fn render(&self, _f: &mut ratatui::Frame<'_>, _state: &AppState) {
        // Will be generated by rune
    }

    fn handle_key(&mut self, _key: crossterm::event::KeyEvent, _state: &mut AppState) {
        // Will be generated by rune
    }
}
