#!/usr/bin/env python3
"""Run TUI in a PTY - keeps TTY open until child exits."""
import os
import sys
import pty
import select
import fcntl
import struct
import termios

def main():
    cwd = os.getcwd()
    cmd = ["./target/debug/runie-tui"]
    
    print("Starting TUI in PTY...", file=sys.stderr, flush=True)
    
    master_fd, slave_fd = pty.openpty()
    slave_name = os.ttyname(slave_fd)
    print(f"PTY: {slave_name}", file=sys.stderr, flush=True)
    
    pid = os.fork()
    if pid == 0:
        # Child process
        os.close(master_fd)
        
        # Set as controlling terminal
        try:
            fcntl.ioctl(slave_fd, termios.TIOCSCTTY, 0)
        except OSError:
            pass
        
        # Redirect stdio to PTY
        os.dup2(slave_fd, 0)
        os.dup2(slave_fd, 1)
        os.dup2(slave_fd, 2)
        os.close(slave_fd)
        
        # Set terminal size
        try:
            winsize = struct.pack('HHHH', 24, 80, 0, 0)
            fcntl.ioctl(0, termios.TIOCSWINSZ, winsize)
        except:
            pass
        
        os.chdir(cwd)
        os.execvp(cmd[0], cmd)
    else:
        # Parent process
        os.close(slave_fd)
        
        # Read output from PTY until child exits
        try:
            while True:
                # Check if child is still alive
                result = os.waitpid(pid, os.WNOHANG)
                if result[0] != 0:
                    break
                
                # Try to read from PTY
                try:
                    r, _, _ = select.select([master_fd], [], [], 0.5)
                    if master_fd in r:
                        data = os.read(master_fd, 4096)
                        if data:
                            sys.stdout.write(data.decode('utf-8', errors='replace'))
                            sys.stdout.flush()
                        else:
                            break
                except OSError:
                    break
        finally:
            # Drain any remaining output
            try:
                import time
                time.sleep(0.5)
                while True:
                    r, _, _ = select.select([master_fd], [], [], 0.1)
                    if master_fd in r:
                        try:
                            data = os.read(master_fd, 4096)
                            if data:
                                sys.stdout.write(data.decode('utf-8', errors='replace'))
                                sys.stdout.flush()
                        except:
                            break
                    else:
                        break
            except:
                pass
            
            os.close(master_fd)
            print("TUI exited", file=sys.stderr, flush=True)

if __name__ == "__main__":
    main()
