runie_core::typed_action_registry! {
    pub enum PaletteAction {
        NewSession => "New Session", KeyboardShortcuts => "Keyboard Shortcuts", Quit => "Quit",
        Changelog => "Changelog", CopyLastResponse => "Copy Last Response", SessionInfo => "Session Info",
        SessionHistory => "Session History", SessionHistoryQuery => "Session History Query", UndoSession => "Undo Session", SelectModel => "Select Model",
        SelectTheme => "Select Theme", ManageProviders => "Manage Providers", ScopedModels => "Scoped Models",
        SetSessionName => "Set Session Name", CompactContext => "Compact Context", CompactContextNow => "Compact Context Now", ForkSession => "Fork Session",
        SelectTreeEntry => "Select Tree Entry", ExportSession => "Export Session", ImportSession => "Import Session",
        CloneSession => "Clone Session", ResumeSession => "Resume Session", ResumeSessionPicker => "Resume Session Picker", ShareSession => "Share Session",
        Help => "Help", ContextInfo => "Context Info", ClearContext => "Clear Context", ResetContext => "Reset Context", ContextPolicy => "Context Policy", ContextPolicyOn => "Enable Context Policy", ContextPolicyOff => "Disable Context Policy", ContextPolicyReserve => "Set Context Reserve", ContextPolicyKeepRecent => "Set Context Keep Recent", Settings => "Settings", Doctor => "Doctor", DoctorInspect => "Inspect Diagnostics", DoctorFix => "Apply Diagnostic Fixes",
        RewindSession => "Rewind Session", PromptHistory => "Prompt History", FindTranscript => "Find Transcript",
        JumpTranscript => "Jump Transcript", Recap => "Recap", SetEffort => "Set Reasoning Effort",
        AlwaysApprove => "Always Approve", AutoApprove => "Automatic Approval", AskBeforeTools => "Ask Before Tools", Deny => "Deny Tools", PlanMode => "Plan Mode",
        ViewPlan => "View Plan", Login => "Login", Logout => "Logout", Reload => "Reload",
        TrustProject => "Trust Project", Skills => "Skills", Hooks => "Hooks", Plugins => "Plugins",
        Mcps => "MCP Servers", CloseMcps => "Close MCP Servers", ReconnectMcps => "Reconnect MCP Servers", McpNotifications => "MCP Notifications", ClearMcpNotifications => "Clear MCP Notifications", McpReady => "Ready MCP Servers", McpFailed => "Failed MCP Servers",
        McpBusy => "Busy MCP Servers", McpClosed => "Closed MCP Servers", McpStdio => "Stdio MCP Servers",
        McpHttp => "HTTP MCP Servers", McpPopNotifications => "Pop MCP Notification", Memory => "Memory", Remember => "Remember", Goal => "Goal",
        Workflow => "Workflow", Workflows => "Workflows", Loop => "Loop", DeepResearch => "Deep Research",
        Feedback => "Feedback", Usage => "Usage", UsageChart => "Usage Chart", UsageChartAll => "Usage Chart All", UsageChartInput => "Usage Chart Input", UsageChartOutput => "Usage Chart Output", UsageChartCost => "Usage Chart Cost", Jobs => "Background Jobs", ActiveJobs => "Active Jobs",
        CancelAllJobs => "Cancel All Jobs", CancelRunningJobs => "Cancel Running Jobs", ClearFinishedJobs => "Clear Finished Jobs", CompletedJobs => "Completed Jobs", QueuedJobs => "Queued Jobs",
        FailedJobs => "Failed Jobs", RunningJobs => "Running Jobs", CancelledJobs => "Cancelled Jobs", CancelQueuedJobs => "Cancel Queued Jobs", JobOutput => "Job Output", JobOutputFacts => "Job Output Facts", JobOutputHead => "Job Output Head", JobOutputTail => "Job Output Tail",
        GitStatus => "Git Status", GitDiff => "Git Diff", GitReview => "Git Review", GitCommitPrepare => "Prepare Git Commit", GitCommit => "Commit Git", GitWorktrees => "Git Worktrees",
        GitConflicts => "Git Conflicts", GitConflictsInspect => "Inspect Git Conflicts", GitConflictsCancel => "Cancel Git Conflict Review", Questions => "User Questions", AnsweredQuestions => "Answered Questions", CancelledQuestions => "Cancelled Questions", RejectedQuestions => "Rejected Questions", ClearQuestionHistory => "Clear Question History", PendingQuestions => "Pending Questions",
    }
}
