// AUTO-GENERATED from taxonomy.json — do not edit manually
// Regenerate: python3 build_scripts/generate_event_taxonomy.py

use super::{Event, EventCategory, EventKind};

impl Event {
    /// Return the [`EventKind`] for this event variant.
    pub fn kind(&self) -> EventKind {
        match self {
            Event::Abort => EventKind::Control,
            Event::ApproveEdit => EventKind::Intent,
            Event::AssistantMessageReady { .. } => EventKind::Fact,
            Event::AtFilePicker => EventKind::Intent,
            Event::AuthLoaded { .. } => EventKind::Fact,
            Event::Backspace => EventKind::Intent,
            Event::BashOutput { .. } => EventKind::Fact,
            Event::Cancel => EventKind::Intent,
            Event::ClearQueues => EventKind::Control,
            Event::ClearTransient => EventKind::Intent,
            Event::ClipboardRead { .. } => EventKind::Fact,
            Event::ClipboardWritten { .. } => EventKind::Fact,
            Event::CloneSession => EventKind::Intent,
            Event::CommandFormBackspace => EventKind::Intent,
            Event::CommandFormClose => EventKind::Intent,
            Event::CommandFormDown => EventKind::Intent,
            Event::CommandFormInput { .. } => EventKind::Intent,
            Event::CommandFormSubmit => EventKind::Intent,
            Event::CommandFormUp => EventKind::Intent,
            Event::CompactionTriggered { .. } => EventKind::Fact,
            Event::CompletionChanged { .. } => EventKind::Fact,
            Event::ConfigLoaded { .. } => EventKind::Fact,
            Event::CopyBlockMetadata => EventKind::Intent,
            Event::CopyLastResponse => EventKind::Control,
            Event::CopySelectedBlock => EventKind::Intent,
            Event::CopyToClipboard { .. } => EventKind::Intent,
            Event::CursorEnd => EventKind::Intent,
            Event::CursorLeft => EventKind::Intent,
            Event::CursorRight => EventKind::Intent,
            Event::CursorStart => EventKind::Intent,
            Event::CursorWordLeft => EventKind::Intent,
            Event::CursorWordRight => EventKind::Intent,
            Event::CycleModelNext => EventKind::Intent,
            Event::CycleModelPrev => EventKind::Intent,
            Event::CycleThinkingLevel => EventKind::Intent,
            Event::DeleteSession { .. } => EventKind::Control,
            Event::DeleteToEnd => EventKind::Intent,
            Event::DeleteToStart => EventKind::Intent,
            Event::DeleteWord => EventKind::Intent,
            Event::Dequeue => EventKind::Control,
            Event::DialogBack => EventKind::Intent,
            Event::Done { .. } => EventKind::Fact,
            Event::Down => EventKind::Intent,
            Event::EnvDetected { .. } => EventKind::Fact,
            Event::Error { .. } => EventKind::Fact,
            Event::Escape => EventKind::Intent,
            Event::ExternalEditorClosed { .. } => EventKind::Fact,
            Event::ExternalEditorDone { .. } => EventKind::Control,
            Event::FffSearchResult { .. } => EventKind::Fact,
            Event::FilesWritten { .. } => EventKind::Fact,
            Event::FocusGained => EventKind::Intent,
            Event::FocusLost => EventKind::Intent,
            Event::FollowUp => EventKind::Control,
            Event::FollowUpDelivered { .. } => EventKind::Fact,
            Event::ForceQuit => EventKind::Control,
            Event::ForkSession { .. } => EventKind::Intent,
            Event::GistShared { .. } => EventKind::Fact,
            Event::GoToBottom => EventKind::Intent,
            Event::GoToTop => EventKind::Intent,
            Event::HistoryAppend { .. } => EventKind::Fact,
            Event::HistoryLoaded { .. } => EventKind::Fact,
            Event::HistoryNext => EventKind::Intent,
            Event::HistoryPrev => EventKind::Intent,
            Event::IdGenerated { .. } => EventKind::Fact,
            Event::Input { .. } => EventKind::Intent,
            Event::InputChanged { .. } => EventKind::Fact,
            Event::InsertAtRef { .. } => EventKind::Intent,
            Event::KeybindingsReloaded => EventKind::Fact,
            Event::KillChar => EventKind::Intent,
            Event::MessageDequeued { .. } => EventKind::Fact,
            Event::MessageReplayed { .. } => EventKind::Fact,
            Event::ModelSelectorBackspace => EventKind::Intent,
            Event::ModelSelectorClose => EventKind::Intent,
            Event::ModelSelectorDown => EventKind::Intent,
            Event::ModelSelectorFilter { .. } => EventKind::Intent,
            Event::ModelSelectorSelect => EventKind::Intent,
            Event::ModelSelectorUp => EventKind::Intent,
            Event::ModelsFetched { .. } => EventKind::Fact,
            Event::MouseScrollDown => EventKind::Intent,
            Event::MouseScrollUp => EventKind::Intent,
            Event::NewSession => EventKind::Control,
            Event::Newline => EventKind::Intent,
            Event::OpenExternalEditor => EventKind::Control,
            Event::OpenSessionList => EventKind::Control,
            Event::PageDown => EventKind::Intent,
            Event::PageUp => EventKind::Intent,
            Event::PaletteBackspace => EventKind::Intent,
            Event::PaletteClose => EventKind::Intent,
            Event::PaletteDown => EventKind::Intent,
            Event::PaletteFilter { .. } => EventKind::Intent,
            Event::PaletteSelect => EventKind::Intent,
            Event::PaletteUp => EventKind::Intent,
            Event::Paste { .. } => EventKind::Intent,
            Event::PasteImage => EventKind::Intent,
            Event::PathCompletionClose => EventKind::Intent,
            Event::PathCompletionDown => EventKind::Intent,
            Event::PathCompletionSelect => EventKind::Intent,
            Event::PathCompletionUp => EventKind::Intent,
            Event::PatternWorkerFinished { .. } => EventKind::Fact,
            Event::PatternWorkerSpawned { .. } => EventKind::Fact,
            Event::PendingEdit { .. } => EventKind::Intent,
            Event::PermissionAllow { .. } => EventKind::Intent,
            Event::PermissionAlwaysAllow { .. } => EventKind::Intent,
            Event::PermissionDeny { .. } => EventKind::Intent,
            Event::PermissionOnce { .. } => EventKind::Intent,
            Event::PermissionRequest { .. } => EventKind::Fact,
            Event::PermissionRequestDismissed => EventKind::Fact,
            Event::PermissionResponse { .. } => EventKind::Intent,
            Event::PermissionSessionAllow { .. } => EventKind::Intent,
            Event::PlanModeDisabled => EventKind::Intent,
            Event::PlanModeEnabled { .. } => EventKind::Intent,
            Event::ProcessResumed => EventKind::Fact,
            Event::ProvidersAdd => EventKind::Intent,
            Event::ProvidersDialog => EventKind::Intent,
            Event::ProvidersDisconnect { .. } => EventKind::Intent,
            Event::ProvidersEditModels { .. } => EventKind::Intent,
            Event::ProvidersSelectModel { .. } => EventKind::Intent,
            Event::QueueAborted { .. } => EventKind::Fact,
            Event::QueueFollowUpAdded { .. } => EventKind::Fact,
            Event::QueueSteeringAdded { .. } => EventKind::Fact,
            Event::QueuesCleared => EventKind::Fact,
            Event::Quit => EventKind::Control,
            Event::ReadOnlyChanged { .. } => EventKind::Fact,
            Event::Redo => EventKind::Intent,
            Event::RejectEdit => EventKind::Intent,
            Event::ReloadAll => EventKind::Intent,
            Event::RenameSession { .. } => EventKind::Control,
            Event::Reset => EventKind::Control,
            Event::Response { .. } => EventKind::Fact,
            Event::ResponseDelta { .. } => EventKind::Fact,
            Event::ResponseDeltaStarted { .. } => EventKind::Fact,
            Event::ResumeSession => EventKind::Control,
            Event::RunCompactCommand { .. } => EventKind::Intent,
            Event::RunDeleteCommand { .. } => EventKind::Intent,
            Event::RunExportCommand { .. } => EventKind::Intent,
            Event::RunForkCommand { .. } => EventKind::Intent,
            Event::RunImportCommand { .. } => EventKind::Intent,
            Event::RunLoadCommand { .. } => EventKind::Intent,
            Event::RunLoginCommand { .. } => EventKind::Intent,
            Event::RunLogoutCommand { .. } => EventKind::Intent,
            Event::RunNameCommand { .. } => EventKind::Intent,
            Event::RunPaletteCommand { .. } => EventKind::Intent,
            Event::RunPromptCommand { .. } => EventKind::Intent,
            Event::RunSaveCommand { .. } => EventKind::Intent,
            Event::RunSkillCommand { .. } => EventKind::Intent,
            Event::RunThinkingCommand { .. } => EventKind::Intent,
            Event::Save => EventKind::Intent,
            Event::ScopedModelDisableAll => EventKind::Intent,
            Event::ScopedModelEnableAll => EventKind::Intent,
            Event::ScopedModelToggle { .. } => EventKind::Intent,
            Event::ScopedModelToggleProvider { .. } => EventKind::Intent,
            Event::SelectModel { .. } => EventKind::Intent,
            Event::SelectProvider { .. } => EventKind::Intent,
            Event::SelectSession { .. } => EventKind::Control,
            Event::SessionChanged { .. } => EventKind::Fact,
            Event::SessionDeleted { .. } => EventKind::Fact,
            Event::SessionExported { .. } => EventKind::Fact,
            Event::SessionImported { .. } => EventKind::Fact,
            Event::SessionList { .. } => EventKind::Fact,
            Event::SessionLoaded { .. } => EventKind::Fact,
            Event::SessionMessageAdded { .. } => EventKind::Fact,
            Event::SessionMessageUpdated { .. } => EventKind::Fact,
            Event::SessionMetadataUpdated { .. } => EventKind::Fact,
            Event::SessionOperationFailed { .. } => EventKind::Fact,
            Event::SessionSaved { .. } => EventKind::Fact,
            Event::SessionTreeFilterCycle => EventKind::Intent,
            Event::SessionTreeSelect { .. } => EventKind::Intent,
            Event::SessionTreeSnapshot { .. } => EventKind::Fact,
            Event::SetMode { .. } => EventKind::Intent,
            Event::SetPrompt { .. } => EventKind::Fact,
            Event::SetThinkingLevel { .. } => EventKind::Intent,
            Event::SettingsClose => EventKind::Intent,
            Event::SettingsDown => EventKind::Intent,
            Event::SettingsLeft => EventKind::Intent,
            Event::SettingsRight => EventKind::Intent,
            Event::SettingsSelect => EventKind::Intent,
            Event::SettingsSwitchCategory { .. } => EventKind::Intent,
            Event::SettingsUp => EventKind::Intent,
            Event::ShareSession => EventKind::Control,
            Event::ShowDiagnostics => EventKind::Intent,
            Event::SkillsLoaded { .. } => EventKind::Fact,
            Event::StarSession { .. } => EventKind::Control,
            Event::Start => EventKind::Intent,
            Event::SteeringDelivered { .. } => EventKind::Fact,
            Event::StreamStarted { .. } => EventKind::Fact,
            Event::Submit => EventKind::Intent,
            Event::SubmitKey { .. } => EventKind::Intent,
            Event::Suspend => EventKind::Control,
            Event::SwitchModel { .. } => EventKind::Intent,
            Event::SwitchModelWithLevel { .. } => EventKind::Intent,
            Event::SwitchTheme { .. } => EventKind::Intent,
            Event::SystemMessage { .. } => EventKind::Fact,
            Event::TerminalSize { .. } => EventKind::Intent,
            Event::TextEnd { .. } => EventKind::Fact,
            Event::TextStart { .. } => EventKind::Fact,
            Event::Thinking { .. } => EventKind::Fact,
            Event::ThinkingDelta { .. } => EventKind::Fact,
            Event::ThinkingEnd { .. } => EventKind::Fact,
            Event::ThinkingStart { .. } => EventKind::Fact,
            Event::ThoughtDone { .. } => EventKind::Fact,
            Event::ToggleCommandPalette => EventKind::Intent,
            Event::ToggleExpand => EventKind::Control,
            Event::ToggleModel { .. } => EventKind::Intent,
            Event::ToggleModelSelector => EventKind::Intent,
            Event::TogglePathCompletion => EventKind::Intent,
            Event::ToggleReadOnly => EventKind::Intent,
            Event::ToggleScopedModelsDialog => EventKind::Intent,
            Event::ToggleSessionTree => EventKind::Intent,
            Event::ToggleSettingsDialog => EventKind::Intent,
            Event::ToggleTasksPane => EventKind::Control,
            Event::ToggleVimMode => EventKind::Control,
            Event::ToggleWelcome => EventKind::Intent,
            Event::TokenStatsUpdated { .. } => EventKind::Fact,
            Event::ToolConstraintError { .. } => EventKind::Fact,
            Event::ToolEnd { .. } => EventKind::Fact,
            Event::ToolInputDelta { .. } => EventKind::Fact,
            Event::ToolRequestsRecorded { .. } => EventKind::Fact,
            Event::ToolStart { .. } => EventKind::Fact,
            Event::TransientError { .. } => EventKind::Intent,
            Event::TransientMessage { .. } => EventKind::Intent,
            Event::TrustChanged { .. } => EventKind::Fact,
            Event::TrustLoaded { .. } => EventKind::Fact,
            Event::TrustProject => EventKind::Intent,
            Event::TrustSet { .. } => EventKind::Fact,
            Event::TurnAborted => EventKind::Fact,
            Event::TurnComplete { .. } => EventKind::Fact,
            Event::TurnCompleted => EventKind::Fact,
            Event::TurnConstraintError { .. } => EventKind::Fact,
            Event::TurnErrored { .. } => EventKind::Fact,
            Event::TurnStarted { .. } => EventKind::Fact,
            Event::Undo => EventKind::Intent,
            Event::UntrustProject => EventKind::Intent,
            Event::Up => EventKind::Intent,
            Event::UserMessageSubmitted { .. } => EventKind::Fact,
            Event::ValidationFailed { .. } => EventKind::Fact,
            Event::ViewChanged { .. } => EventKind::Fact,
        }
    }

    /// Return the [`EventCategory`] for this event variant.
    pub fn category(&self) -> EventCategory {
        match self {
            Event::Abort => EventCategory::Control,
            Event::ApproveEdit => EventCategory::Edit,
            Event::AssistantMessageReady { .. } => EventCategory::Agent,
            Event::AtFilePicker => EventCategory::Dialog,
            Event::AuthLoaded { .. } => EventCategory::IO,
            Event::Backspace => EventCategory::Input,
            Event::BashOutput { .. } => EventCategory::IO,
            Event::Cancel => EventCategory::LoginFlow,
            Event::ClearQueues => EventCategory::Control,
            Event::ClearTransient => EventCategory::System,
            Event::ClipboardRead { .. } => EventCategory::IO,
            Event::ClipboardWritten { .. } => EventCategory::IO,
            Event::CloneSession => EventCategory::Session,
            Event::CommandFormBackspace => EventCategory::Dialog,
            Event::CommandFormClose => EventCategory::Dialog,
            Event::CommandFormDown => EventCategory::Dialog,
            Event::CommandFormInput { .. } => EventCategory::Dialog,
            Event::CommandFormSubmit => EventCategory::Dialog,
            Event::CommandFormUp => EventCategory::Dialog,
            Event::CompactionTriggered { .. } => EventCategory::Agent,
            Event::CompletionChanged { .. } => EventCategory::Persistence,
            Event::ConfigLoaded { .. } => EventCategory::System,
            Event::CopyBlockMetadata => EventCategory::Dialog,
            Event::CopyLastResponse => EventCategory::Control,
            Event::CopySelectedBlock => EventCategory::Dialog,
            Event::CopyToClipboard { .. } => EventCategory::Dialog,
            Event::CursorEnd => EventCategory::Input,
            Event::CursorLeft => EventCategory::Input,
            Event::CursorRight => EventCategory::Input,
            Event::CursorStart => EventCategory::Input,
            Event::CursorWordLeft => EventCategory::Input,
            Event::CursorWordRight => EventCategory::Input,
            Event::CycleModelNext => EventCategory::ModelConfig,
            Event::CycleModelPrev => EventCategory::ModelConfig,
            Event::CycleThinkingLevel => EventCategory::ModelConfig,
            Event::DeleteSession { .. } => EventCategory::Control,
            Event::DeleteToEnd => EventCategory::Input,
            Event::DeleteToStart => EventCategory::Input,
            Event::DeleteWord => EventCategory::Input,
            Event::Dequeue => EventCategory::Control,
            Event::DialogBack => EventCategory::Dialog,
            Event::Done { .. } => EventCategory::Agent,
            Event::Down => EventCategory::Scroll,
            Event::EnvDetected { .. } => EventCategory::IO,
            Event::Error { .. } => EventCategory::Agent,
            Event::Escape => EventCategory::Input,
            Event::ExternalEditorClosed { .. } => EventCategory::IO,
            Event::ExternalEditorDone { .. } => EventCategory::Control,
            Event::FffSearchResult { .. } => EventCategory::IO,
            Event::FilesWritten { .. } => EventCategory::IO,
            Event::FocusGained => EventCategory::Input,
            Event::FocusLost => EventCategory::Input,
            Event::FollowUp => EventCategory::Control,
            Event::FollowUpDelivered { .. } => EventCategory::Agent,
            Event::ForceQuit => EventCategory::Control,
            Event::ForkSession { .. } => EventCategory::Session,
            Event::GistShared { .. } => EventCategory::IO,
            Event::GoToBottom => EventCategory::Input,
            Event::GoToTop => EventCategory::Input,
            Event::HistoryAppend { .. } => EventCategory::Persistence,
            Event::HistoryLoaded { .. } => EventCategory::Persistence,
            Event::HistoryNext => EventCategory::Input,
            Event::HistoryPrev => EventCategory::Input,
            Event::IdGenerated { .. } => EventCategory::Agent,
            Event::Input { .. } => EventCategory::Input,
            Event::InputChanged { .. } => EventCategory::Persistence,
            Event::InsertAtRef { .. } => EventCategory::Dialog,
            Event::KeybindingsReloaded => EventCategory::ModelConfig,
            Event::KillChar => EventCategory::Input,
            Event::MessageDequeued { .. } => EventCategory::Agent,
            Event::MessageReplayed { .. } => EventCategory::Other,
            Event::ModelSelectorBackspace => EventCategory::Dialog,
            Event::ModelSelectorClose => EventCategory::Dialog,
            Event::ModelSelectorDown => EventCategory::Dialog,
            Event::ModelSelectorFilter { .. } => EventCategory::Dialog,
            Event::ModelSelectorSelect => EventCategory::Dialog,
            Event::ModelSelectorUp => EventCategory::Dialog,
            Event::ModelsFetched { .. } => EventCategory::LoginFlow,
            Event::MouseScrollDown => EventCategory::Input,
            Event::MouseScrollUp => EventCategory::Input,
            Event::NewSession => EventCategory::Control,
            Event::Newline => EventCategory::Input,
            Event::OpenExternalEditor => EventCategory::Control,
            Event::OpenSessionList => EventCategory::Control,
            Event::PageDown => EventCategory::Input,
            Event::PageUp => EventCategory::Input,
            Event::PaletteBackspace => EventCategory::Dialog,
            Event::PaletteClose => EventCategory::Dialog,
            Event::PaletteDown => EventCategory::Dialog,
            Event::PaletteFilter { .. } => EventCategory::Dialog,
            Event::PaletteSelect => EventCategory::Dialog,
            Event::PaletteUp => EventCategory::Dialog,
            Event::Paste { .. } => EventCategory::Input,
            Event::PasteImage => EventCategory::Input,
            Event::PathCompletionClose => EventCategory::Dialog,
            Event::PathCompletionDown => EventCategory::Dialog,
            Event::PathCompletionSelect => EventCategory::Dialog,
            Event::PathCompletionUp => EventCategory::Dialog,
            Event::PatternWorkerFinished { .. } => EventCategory::Agent,
            Event::PatternWorkerSpawned { .. } => EventCategory::Agent,
            Event::PendingEdit { .. } => EventCategory::Edit,
            Event::PermissionAllow { .. } => EventCategory::Permission,
            Event::PermissionAlwaysAllow { .. } => EventCategory::Permission,
            Event::PermissionDeny { .. } => EventCategory::Permission,
            Event::PermissionOnce { .. } => EventCategory::Permission,
            Event::PermissionRequest { .. } => EventCategory::Permission,
            Event::PermissionRequestDismissed => EventCategory::Permission,
            Event::PermissionResponse { .. } => EventCategory::Permission,
            Event::PermissionSessionAllow { .. } => EventCategory::Permission,
            Event::PlanModeDisabled => EventCategory::PlanMode,
            Event::PlanModeEnabled { .. } => EventCategory::PlanMode,
            Event::ProcessResumed => EventCategory::IO,
            Event::ProvidersAdd => EventCategory::Dialog,
            Event::ProvidersDialog => EventCategory::Dialog,
            Event::ProvidersDisconnect { .. } => EventCategory::Dialog,
            Event::ProvidersEditModels { .. } => EventCategory::Dialog,
            Event::ProvidersSelectModel { .. } => EventCategory::Dialog,
            Event::QueueAborted { .. } => EventCategory::Agent,
            Event::QueueFollowUpAdded { .. } => EventCategory::Agent,
            Event::QueueSteeringAdded { .. } => EventCategory::Agent,
            Event::QueuesCleared => EventCategory::Agent,
            Event::Quit => EventCategory::Control,
            Event::ReadOnlyChanged { .. } => EventCategory::Persistence,
            Event::Redo => EventCategory::Input,
            Event::RejectEdit => EventCategory::Edit,
            Event::ReloadAll => EventCategory::ModelConfig,
            Event::RenameSession { .. } => EventCategory::Control,
            Event::Reset => EventCategory::Control,
            Event::Response { .. } => EventCategory::Agent,
            Event::ResponseDelta { .. } => EventCategory::Agent,
            Event::ResponseDeltaStarted { .. } => EventCategory::Agent,
            Event::ResumeSession => EventCategory::Control,
            Event::RunCompactCommand { .. } => EventCategory::Command,
            Event::RunDeleteCommand { .. } => EventCategory::Command,
            Event::RunExportCommand { .. } => EventCategory::Command,
            Event::RunForkCommand { .. } => EventCategory::Command,
            Event::RunImportCommand { .. } => EventCategory::Command,
            Event::RunLoadCommand { .. } => EventCategory::Command,
            Event::RunLoginCommand { .. } => EventCategory::Command,
            Event::RunLogoutCommand { .. } => EventCategory::Command,
            Event::RunNameCommand { .. } => EventCategory::Command,
            Event::RunPaletteCommand { .. } => EventCategory::Command,
            Event::RunPromptCommand { .. } => EventCategory::Command,
            Event::RunSaveCommand { .. } => EventCategory::Command,
            Event::RunSkillCommand { .. } => EventCategory::Command,
            Event::RunThinkingCommand { .. } => EventCategory::Command,
            Event::Save => EventCategory::LoginFlow,
            Event::ScopedModelDisableAll => EventCategory::ModelConfig,
            Event::ScopedModelEnableAll => EventCategory::ModelConfig,
            Event::ScopedModelToggle { .. } => EventCategory::ModelConfig,
            Event::ScopedModelToggleProvider { .. } => EventCategory::ModelConfig,
            Event::SelectModel { .. } => EventCategory::ModelConfig,
            Event::SelectProvider { .. } => EventCategory::LoginFlow,
            Event::SelectSession { .. } => EventCategory::Control,
            Event::SessionChanged { .. } => EventCategory::Session,
            Event::SessionDeleted { .. } => EventCategory::Session,
            Event::SessionExported { .. } => EventCategory::Session,
            Event::SessionImported { .. } => EventCategory::Session,
            Event::SessionList { .. } => EventCategory::Session,
            Event::SessionLoaded { .. } => EventCategory::Session,
            Event::SessionMessageAdded { .. } => EventCategory::Session,
            Event::SessionMessageUpdated { .. } => EventCategory::Session,
            Event::SessionMetadataUpdated { .. } => EventCategory::Session,
            Event::SessionOperationFailed { .. } => EventCategory::Session,
            Event::SessionSaved { .. } => EventCategory::Session,
            Event::SessionTreeFilterCycle => EventCategory::Session,
            Event::SessionTreeSelect { .. } => EventCategory::Session,
            Event::SessionTreeSnapshot { .. } => EventCategory::Session,
            Event::SetMode { .. } => EventCategory::ModelConfig,
            Event::SetPrompt { .. } => EventCategory::Command,
            Event::SetThinkingLevel { .. } => EventCategory::ModelConfig,
            Event::SettingsClose => EventCategory::ModelConfig,
            Event::SettingsDown => EventCategory::ModelConfig,
            Event::SettingsLeft => EventCategory::ModelConfig,
            Event::SettingsRight => EventCategory::ModelConfig,
            Event::SettingsSelect => EventCategory::ModelConfig,
            Event::SettingsSwitchCategory { .. } => EventCategory::ModelConfig,
            Event::SettingsUp => EventCategory::ModelConfig,
            Event::ShareSession => EventCategory::Control,
            Event::ShowDiagnostics => EventCategory::System,
            Event::SkillsLoaded { .. } => EventCategory::IO,
            Event::StarSession { .. } => EventCategory::Control,
            Event::Start => EventCategory::LoginFlow,
            Event::SteeringDelivered { .. } => EventCategory::Agent,
            Event::StreamStarted { .. } => EventCategory::Agent,
            Event::Submit => EventCategory::Input,
            Event::SubmitKey { .. } => EventCategory::LoginFlow,
            Event::Suspend => EventCategory::Control,
            Event::SwitchModel { .. } => EventCategory::ModelConfig,
            Event::SwitchModelWithLevel { .. } => EventCategory::ModelConfig,
            Event::SwitchTheme { .. } => EventCategory::ModelConfig,
            Event::SystemMessage { .. } => EventCategory::System,
            Event::TerminalSize { .. } => EventCategory::Input,
            Event::TextEnd { .. } => EventCategory::Agent,
            Event::TextStart { .. } => EventCategory::Agent,
            Event::Thinking { .. } => EventCategory::Agent,
            Event::ThinkingDelta { .. } => EventCategory::Agent,
            Event::ThinkingEnd { .. } => EventCategory::Agent,
            Event::ThinkingStart { .. } => EventCategory::Agent,
            Event::ThoughtDone { .. } => EventCategory::Agent,
            Event::ToggleCommandPalette => EventCategory::Dialog,
            Event::ToggleExpand => EventCategory::Control,
            Event::ToggleModel { .. } => EventCategory::LoginFlow,
            Event::ToggleModelSelector => EventCategory::Dialog,
            Event::TogglePathCompletion => EventCategory::Dialog,
            Event::ToggleReadOnly => EventCategory::ModelConfig,
            Event::ToggleScopedModelsDialog => EventCategory::ModelConfig,
            Event::ToggleSessionTree => EventCategory::Session,
            Event::ToggleSettingsDialog => EventCategory::ModelConfig,
            Event::ToggleTasksPane => EventCategory::Control,
            Event::ToggleVimMode => EventCategory::Control,
            Event::ToggleWelcome => EventCategory::Dialog,
            Event::TokenStatsUpdated { .. } => EventCategory::Agent,
            Event::ToolConstraintError { .. } => EventCategory::Agent,
            Event::ToolEnd { .. } => EventCategory::Agent,
            Event::ToolInputDelta { .. } => EventCategory::Agent,
            Event::ToolRequestsRecorded { .. } => EventCategory::Agent,
            Event::ToolStart { .. } => EventCategory::Agent,
            Event::TransientError { .. } => EventCategory::System,
            Event::TransientMessage { .. } => EventCategory::System,
            Event::TrustChanged { .. } => EventCategory::Persistence,
            Event::TrustLoaded { .. } => EventCategory::Persistence,
            Event::TrustProject => EventCategory::ModelConfig,
            Event::TrustSet { .. } => EventCategory::Persistence,
            Event::TurnAborted => EventCategory::Agent,
            Event::TurnComplete { .. } => EventCategory::Agent,
            Event::TurnCompleted => EventCategory::Agent,
            Event::TurnConstraintError { .. } => EventCategory::Agent,
            Event::TurnErrored { .. } => EventCategory::Agent,
            Event::TurnStarted { .. } => EventCategory::Agent,
            Event::Undo => EventCategory::Input,
            Event::UntrustProject => EventCategory::ModelConfig,
            Event::Up => EventCategory::Scroll,
            Event::UserMessageSubmitted { .. } => EventCategory::Agent,
            Event::ValidationFailed { .. } => EventCategory::LoginFlow,
            Event::ViewChanged { .. } => EventCategory::Persistence,
        }
    }

    /// Convert this event to an intent [`Event`], if it maps to one.
    ///
    /// Returns `None` for Fact variants. Control variants like Quit, Reset, Abort
    /// are also convertible to intent.
    pub fn into_intent(self) -> Option<Event> {
        match self {
            Event::RunCompactCommand { .. } => Some(self.clone()),
            Event::RunDeleteCommand { .. } => Some(self.clone()),
            Event::RunExportCommand { .. } => Some(self.clone()),
            Event::RunForkCommand { .. } => Some(self.clone()),
            Event::RunImportCommand { .. } => Some(self.clone()),
            Event::RunLoadCommand { .. } => Some(self.clone()),
            Event::RunLoginCommand { .. } => Some(self.clone()),
            Event::RunLogoutCommand { .. } => Some(self.clone()),
            Event::RunNameCommand { .. } => Some(self.clone()),
            Event::RunPaletteCommand { .. } => Some(self.clone()),
            Event::RunPromptCommand { .. } => Some(self.clone()),
            Event::RunSaveCommand { .. } => Some(self.clone()),
            Event::RunSkillCommand { .. } => Some(self.clone()),
            Event::RunThinkingCommand { .. } => Some(self.clone()),
            Event::Abort => Some(self),
            Event::ClearQueues => Some(self),
            Event::CopyLastResponse => Some(self),
            Event::DeleteSession { .. } => Some(self.clone()),
            Event::Dequeue => Some(self),
            Event::ExternalEditorDone { .. } => Some(self.clone()),
            Event::FollowUp => Some(self),
            Event::ForceQuit => Some(self),
            Event::NewSession => Some(self),
            Event::OpenExternalEditor => Some(self),
            Event::OpenSessionList => Some(self),
            Event::Quit => Some(self),
            Event::RenameSession { .. } => Some(self.clone()),
            Event::Reset => Some(self),
            Event::ResumeSession => Some(self),
            Event::SelectSession { .. } => Some(self.clone()),
            Event::ShareSession => Some(self),
            Event::StarSession { .. } => Some(self.clone()),
            Event::Suspend => Some(self),
            Event::ToggleExpand => Some(self),
            Event::ToggleTasksPane => Some(self),
            Event::ToggleVimMode => Some(self),
            Event::AtFilePicker => Some(self),
            Event::CommandFormBackspace => Some(self),
            Event::CommandFormClose => Some(self),
            Event::CommandFormDown => Some(self),
            Event::CommandFormInput { .. } => Some(self.clone()),
            Event::CommandFormSubmit => Some(self),
            Event::CommandFormUp => Some(self),
            Event::CopyBlockMetadata => Some(self),
            Event::CopySelectedBlock => Some(self),
            Event::CopyToClipboard { .. } => Some(self.clone()),
            Event::DialogBack => Some(self),
            Event::InsertAtRef { .. } => Some(self.clone()),
            Event::ModelSelectorBackspace => Some(self),
            Event::ModelSelectorClose => Some(self),
            Event::ModelSelectorDown => Some(self),
            Event::ModelSelectorFilter { .. } => Some(self.clone()),
            Event::ModelSelectorSelect => Some(self),
            Event::ModelSelectorUp => Some(self),
            Event::PaletteBackspace => Some(self),
            Event::PaletteClose => Some(self),
            Event::PaletteDown => Some(self),
            Event::PaletteFilter { .. } => Some(self.clone()),
            Event::PaletteSelect => Some(self),
            Event::PaletteUp => Some(self),
            Event::PathCompletionClose => Some(self),
            Event::PathCompletionDown => Some(self),
            Event::PathCompletionSelect => Some(self),
            Event::PathCompletionUp => Some(self),
            Event::ProvidersAdd => Some(self),
            Event::ProvidersDialog => Some(self),
            Event::ProvidersDisconnect { .. } => Some(self.clone()),
            Event::ProvidersEditModels { .. } => Some(self.clone()),
            Event::ProvidersSelectModel { .. } => Some(self.clone()),
            Event::ToggleCommandPalette => Some(self),
            Event::ToggleModelSelector => Some(self),
            Event::TogglePathCompletion => Some(self),
            Event::ToggleWelcome => Some(self),
            Event::ApproveEdit => Some(self),
            Event::PendingEdit { .. } => Some(self.clone()),
            Event::RejectEdit => Some(self),
            Event::Backspace => Some(self),
            Event::CursorEnd => Some(self),
            Event::CursorLeft => Some(self),
            Event::CursorRight => Some(self),
            Event::CursorStart => Some(self),
            Event::CursorWordLeft => Some(self),
            Event::CursorWordRight => Some(self),
            Event::DeleteToEnd => Some(self),
            Event::DeleteToStart => Some(self),
            Event::DeleteWord => Some(self),
            Event::Escape => Some(self),
            Event::FocusGained => Some(self),
            Event::FocusLost => Some(self),
            Event::GoToBottom => Some(self),
            Event::GoToTop => Some(self),
            Event::HistoryNext => Some(self),
            Event::HistoryPrev => Some(self),
            Event::Input { .. } => Some(self.clone()),
            Event::KillChar => Some(self),
            Event::MouseScrollDown => Some(self),
            Event::MouseScrollUp => Some(self),
            Event::Newline => Some(self),
            Event::PageDown => Some(self),
            Event::PageUp => Some(self),
            Event::Paste { .. } => Some(self.clone()),
            Event::PasteImage => Some(self),
            Event::Redo => Some(self),
            Event::Submit => Some(self),
            Event::TerminalSize { .. } => Some(self.clone()),
            Event::Undo => Some(self),
            Event::Cancel => Some(self),
            Event::Save => Some(self),
            Event::SelectProvider { .. } => Some(self.clone()),
            Event::Start => Some(self),
            Event::SubmitKey { .. } => Some(self.clone()),
            Event::ToggleModel { .. } => Some(self.clone()),
            Event::CycleModelNext => Some(self),
            Event::CycleModelPrev => Some(self),
            Event::CycleThinkingLevel => Some(self),
            Event::ReloadAll => Some(self),
            Event::ScopedModelDisableAll => Some(self),
            Event::ScopedModelEnableAll => Some(self),
            Event::ScopedModelToggle { .. } => Some(self.clone()),
            Event::ScopedModelToggleProvider { .. } => Some(self.clone()),
            Event::SelectModel { .. } => Some(self.clone()),
            Event::SetMode { .. } => Some(self.clone()),
            Event::SetThinkingLevel { .. } => Some(self.clone()),
            Event::SettingsClose => Some(self),
            Event::SettingsDown => Some(self),
            Event::SettingsLeft => Some(self),
            Event::SettingsRight => Some(self),
            Event::SettingsSelect => Some(self),
            Event::SettingsSwitchCategory { .. } => Some(self.clone()),
            Event::SettingsUp => Some(self),
            Event::SwitchModel { .. } => Some(self.clone()),
            Event::SwitchModelWithLevel { .. } => Some(self.clone()),
            Event::SwitchTheme { .. } => Some(self.clone()),
            Event::ToggleReadOnly => Some(self),
            Event::ToggleScopedModelsDialog => Some(self),
            Event::ToggleSettingsDialog => Some(self),
            Event::TrustProject => Some(self),
            Event::UntrustProject => Some(self),
            Event::PermissionAllow { .. } => Some(self.clone()),
            Event::PermissionAlwaysAllow { .. } => Some(self.clone()),
            Event::PermissionDeny { .. } => Some(self.clone()),
            Event::PermissionOnce { .. } => Some(self.clone()),
            Event::PermissionResponse { .. } => Some(self.clone()),
            Event::PermissionSessionAllow { .. } => Some(self.clone()),
            Event::PlanModeDisabled => Some(self),
            Event::PlanModeEnabled { .. } => Some(self.clone()),
            Event::Down => Some(self),
            Event::Up => Some(self),
            Event::CloneSession => Some(self),
            Event::ForkSession { .. } => Some(self.clone()),
            Event::SessionTreeFilterCycle => Some(self),
            Event::SessionTreeSelect { .. } => Some(self.clone()),
            Event::ToggleSessionTree => Some(self),
            Event::ClearTransient => Some(self),
            Event::ShowDiagnostics => Some(self),
            Event::TransientError { .. } => Some(self.clone()),
            Event::TransientMessage { .. } => Some(self.clone()),
            _ => None,
        }
    }
}

/// Returns true if this event is a fact (not an intent or control).
pub fn is_fact_variant(e: &Event) -> bool {
    matches!(
        e,
            | Event::AssistantMessageReady { .. }
            | Event::CompactionTriggered { .. }
            | Event::Done { .. }
            | Event::Error { .. }
            | Event::FollowUpDelivered { .. }
            | Event::IdGenerated { .. }
            | Event::MessageDequeued { .. }
            | Event::PatternWorkerFinished { .. }
            | Event::PatternWorkerSpawned { .. }
            | Event::QueueAborted { .. }
            | Event::QueueFollowUpAdded { .. }
            | Event::QueueSteeringAdded { .. }
            | Event::QueuesCleared
            | Event::Response { .. }
            | Event::ResponseDelta { .. }
            | Event::ResponseDeltaStarted { .. }
            | Event::SteeringDelivered { .. }
            | Event::StreamStarted { .. }
            | Event::TextEnd { .. }
            | Event::TextStart { .. }
            | Event::Thinking { .. }
            | Event::ThinkingDelta { .. }
            | Event::ThinkingEnd { .. }
            | Event::ThinkingStart { .. }
            | Event::ThoughtDone { .. }
            | Event::TokenStatsUpdated { .. }
            | Event::ToolConstraintError { .. }
            | Event::ToolEnd { .. }
            | Event::ToolInputDelta { .. }
            | Event::ToolRequestsRecorded { .. }
            | Event::ToolStart { .. }
            | Event::TurnAborted
            | Event::TurnComplete { .. }
            | Event::TurnCompleted
            | Event::TurnConstraintError { .. }
            | Event::TurnErrored { .. }
            | Event::TurnStarted { .. }
            | Event::UserMessageSubmitted { .. }
            | Event::SetPrompt { .. }
            | Event::AuthLoaded { .. }
            | Event::BashOutput { .. }
            | Event::ClipboardRead { .. }
            | Event::ClipboardWritten { .. }
            | Event::EnvDetected { .. }
            | Event::ExternalEditorClosed { .. }
            | Event::FffSearchResult { .. }
            | Event::FilesWritten { .. }
            | Event::GistShared { .. }
            | Event::ProcessResumed
            | Event::SkillsLoaded { .. }
            | Event::ModelsFetched { .. }
            | Event::ValidationFailed { .. }
            | Event::KeybindingsReloaded
            | Event::MessageReplayed { .. }
            | Event::PermissionRequest { .. }
            | Event::PermissionRequestDismissed
            | Event::CompletionChanged { .. }
            | Event::HistoryAppend { .. }
            | Event::HistoryLoaded { .. }
            | Event::InputChanged { .. }
            | Event::ReadOnlyChanged { .. }
            | Event::TrustChanged { .. }
            | Event::TrustLoaded { .. }
            | Event::TrustSet { .. }
            | Event::ViewChanged { .. }
            | Event::SessionChanged { .. }
            | Event::SessionDeleted { .. }
            | Event::SessionExported { .. }
            | Event::SessionImported { .. }
            | Event::SessionList { .. }
            | Event::SessionLoaded { .. }
            | Event::SessionMessageAdded { .. }
            | Event::SessionMessageUpdated { .. }
            | Event::SessionMetadataUpdated { .. }
            | Event::SessionOperationFailed { .. }
            | Event::SessionSaved { .. }
            | Event::SessionTreeSnapshot { .. }
            | Event::ConfigLoaded { .. }
            | Event::SystemMessage { .. }
    )
}

// ─────────────────────────────────────────────────────────────────────────────
// EVENT_NAMES — zero-arg constructor table for bindable variants
// ─────────────────────────────────────────────────────────────────────────────

/// Zero-argument event constructor signature.
pub type EventCtor = fn() -> Event;

/// Bindable event names paired with their zero-arg constructors.
///
/// These are events that can be constructed with no arguments, used for
/// keybinding resolution and command palette lookup.
pub const EVENT_NAMES: &[(&str, EventCtor)] = &[
    ("ToggleWelcome", || Event::ToggleWelcome),
    ("ToggleCommandPalette", || Event::ToggleCommandPalette),
    ("PaletteBackspace", || Event::PaletteBackspace),
    ("PaletteUp", || Event::PaletteUp),
    ("PaletteDown", || Event::PaletteDown),
    ("PaletteSelect", || Event::PaletteSelect),
    ("PaletteClose", || Event::PaletteClose),
    ("ToggleModelSelector", || Event::ToggleModelSelector),
    ("ModelSelectorBackspace", || Event::ModelSelectorBackspace),
    ("ModelSelectorUp", || Event::ModelSelectorUp),
    ("ModelSelectorDown", || Event::ModelSelectorDown),
    ("ModelSelectorSelect", || Event::ModelSelectorSelect),
    ("ModelSelectorClose", || Event::ModelSelectorClose),
    ("TogglePathCompletion", || Event::TogglePathCompletion),
    ("PathCompletionUp", || Event::PathCompletionUp),
    ("PathCompletionDown", || Event::PathCompletionDown),
    ("PathCompletionSelect", || Event::PathCompletionSelect),
    ("PathCompletionClose", || Event::PathCompletionClose),
    ("CommandFormBackspace", || Event::CommandFormBackspace),
    ("CommandFormUp", || Event::CommandFormUp),
    ("CommandFormDown", || Event::CommandFormDown),
    ("CommandFormSubmit", || Event::CommandFormSubmit),
    ("CommandFormClose", || Event::CommandFormClose),
    ("DialogBack", || Event::DialogBack),
    ("ProvidersDialog", || Event::ProvidersDialog),
    ("ProvidersAdd", || Event::ProvidersAdd),
    ("CopySelectedBlock", || Event::CopySelectedBlock),
    ("CopyBlockMetadata", || Event::CopyBlockMetadata),
    ("AtFilePicker", || Event::AtFilePicker),
    ("ApproveEdit", || Event::ApproveEdit),
    ("RejectEdit", || Event::RejectEdit),
    ("Backspace", || Event::Backspace),
    ("Newline", || Event::Newline),
    ("Submit", || Event::Submit),
    ("Escape", || Event::Escape),
    ("CursorLeft", || Event::CursorLeft),
    ("CursorRight", || Event::CursorRight),
    ("CursorStart", || Event::CursorStart),
    ("CursorEnd", || Event::CursorEnd),
    ("DeleteWord", || Event::DeleteWord),
    ("DeleteToEnd", || Event::DeleteToEnd),
    ("DeleteToStart", || Event::DeleteToStart),
    ("KillChar", || Event::KillChar),
    ("HistoryPrev", || Event::HistoryPrev),
    ("HistoryNext", || Event::HistoryNext),
    ("Undo", || Event::Undo),
    ("Redo", || Event::Redo),
    ("CursorWordLeft", || Event::CursorWordLeft),
    ("CursorWordRight", || Event::CursorWordRight),
    ("PageUp", || Event::PageUp),
    ("PageDown", || Event::PageDown),
    ("GoToTop", || Event::GoToTop),
    ("GoToBottom", || Event::GoToBottom),
    ("PasteImage", || Event::PasteImage),
    ("MouseScrollUp", || Event::MouseScrollUp),
    ("MouseScrollDown", || Event::MouseScrollDown),
    ("FocusGained", || Event::FocusGained),
    ("FocusLost", || Event::FocusLost),
    ("Start", || Event::Start),
    ("Save", || Event::Save),
    ("Cancel", || Event::Cancel),
    ("CycleModelNext", || Event::CycleModelNext),
    ("CycleModelPrev", || Event::CycleModelPrev),
    ("ToggleScopedModelsDialog", || Event::ToggleScopedModelsDialog),
    ("ScopedModelEnableAll", || Event::ScopedModelEnableAll),
    ("ScopedModelDisableAll", || Event::ScopedModelDisableAll),
    ("ToggleSettingsDialog", || Event::ToggleSettingsDialog),
    ("SettingsUp", || Event::SettingsUp),
    ("SettingsDown", || Event::SettingsDown),
    ("SettingsLeft", || Event::SettingsLeft),
    ("SettingsRight", || Event::SettingsRight),
    ("SettingsSelect", || Event::SettingsSelect),
    ("SettingsClose", || Event::SettingsClose),
    ("CycleThinkingLevel", || Event::CycleThinkingLevel),
    ("ToggleReadOnly", || Event::ToggleReadOnly),
    ("TrustProject", || Event::TrustProject),
    ("UntrustProject", || Event::UntrustProject),
    ("ReloadAll", || Event::ReloadAll),
    ("Up", || Event::Up),
    ("Down", || Event::Down),
    ("CloneSession", || Event::CloneSession),
    ("ToggleSessionTree", || Event::ToggleSessionTree),
    ("SessionTreeFilterCycle", || Event::SessionTreeFilterCycle),
    ("ClearTransient", || Event::ClearTransient),
    ("ShowDiagnostics", || Event::ShowDiagnostics),
    ("Quit", || Event::Quit),
    ("ForceQuit", || Event::ForceQuit),
    ("Reset", || Event::Reset),
    ("Abort", || Event::Abort),
    ("ClearQueues", || Event::ClearQueues),
    ("FollowUp", || Event::FollowUp),
    ("ToggleExpand", || Event::ToggleExpand),
    ("ToggleTasksPane", || Event::ToggleTasksPane),
    ("Dequeue", || Event::Dequeue),
    ("OpenExternalEditor", || Event::OpenExternalEditor),
    ("ShareSession", || Event::ShareSession),
    ("Suspend", || Event::Suspend),
    ("ToggleVimMode", || Event::ToggleVimMode),
    ("CopyLastResponse", || Event::CopyLastResponse),
    ("OpenSessionList", || Event::OpenSessionList),
    ("NewSession", || Event::NewSession),
    ("ResumeSession", || Event::ResumeSession),
];

// ─────────────────────────────────────────────────────────────────────────────
// Helper constructors for variants with optional fields
// ─────────────────────────────────────────────────────────────────────────────

impl Event {
    /// Create a Response with default durable fields.
    pub fn response(id: impl Into<String>, content: impl Into<String>) -> Self {
        Event::Response {
            id: id.into(),
            content: content.into(),
            role: String::new(),
            timestamp: 0.0,
            provider: String::new(),
        }
    }

    /// Create a ToolEnd with default input field.
    pub fn tool_end(
        id: impl Into<String>,
        duration_secs: f64,
        output: impl Into<String>,
    ) -> Self {
        Event::ToolEnd {
            id: id.into(),
            input: None,
            duration_secs,
            output: output.into(),
        }
    }
}
