//! Canonical event name mapping for bindable variants.
//!
//! Named variants are those with zero arguments that appear in `EVENT_NAMES`.
//! Generated by `build.rs` from `taxonomy.json`.

use super::Event;
use crate::event::EVENT_NAMES;

impl Event {
    /// Canonical string name for bindable variants (those in EVENT_NAMES).
    pub fn name(&self) -> Option<&'static str> {
        // Check if this variant is in EVENT_NAMES by comparing names.
        let self_name: &'static str = self.into();
        for (name, _) in EVENT_NAMES {
            if *name == self_name {
                return Some(self_name);
            }
        }
        None
    }

    /// Build an Event from its canonical name. Supports `Input:<char>` prefix.
    pub fn from_name(name: &str) -> Option<Event> {
        if let Some(rest) = name.strip_prefix("Input:") {
            let c = rest.chars().next()?;
            return Some(Event::Input(c));
        }
        for (n, ctor) in EVENT_NAMES {
            if *n == name {
                return Some(ctor());
            }
        }
        None
    }
}
