//! Goal Planner — decomposes a goal into structured tasks.
//!
//! The planner takes a user's goal and uses a structured approach to
//! decompose it into numbered tasks. It runs in the main session (not
//! as a separate subagent) for simplicity, generating a task list
//! that can be executed iteratively.

use crate::goal::{Checkpoint, GoalState};

/// Task generated by the goal planner.
#[derive(Debug, Clone)]
pub struct PlannedTask {
    /// Unique task identifier.
    pub id: String,
    /// Task description.
    pub description: String,
    /// Whether this task has been completed.
    pub completed: bool,
}

/// Result of goal planning.
#[derive(Debug, Clone)]
pub struct PlanResult {
    /// The generated tasks.
    pub tasks: Vec<PlannedTask>,
    /// Summary of the plan approach.
    pub approach: String,
}

/// Goal planner — decomposes a goal into a structured task list.
#[derive(Debug, Default)]
pub struct GoalPlanner;

impl GoalPlanner {
    /// Create a new goal planner.
    pub fn new() -> Self {
        Self
    }

    /// Create a plan from the goal's objective.
    /// Returns a structured task list with the approach summary.
    pub fn plan(&self, goal: &GoalState) -> PlanResult {
        let objective = &goal.objective;

        // Simple task decomposition based on common patterns
        let tasks = self.decompose_objective(objective);
        let approach = self.summarize_approach(objective);

        PlanResult { tasks, approach }
    }

    /// Decompose an objective into tasks.
    fn decompose_objective(&self, objective: &str) -> Vec<PlannedTask> {
        let objective_lower = objective.to_lowercase();

        // Common goal patterns
        if objective_lower.contains("test") && objective_lower.contains("implement") {
            vec![
                PlannedTask::new("1-analyze", "Analyze requirements and understand scope"),
                PlannedTask::new("2-plan", "Create implementation plan"),
                PlannedTask::new("3-implement", "Implement the solution"),
                PlannedTask::new("4-test", "Write and run tests"),
                PlannedTask::new("5-review", "Review and refine"),
            ]
        } else if objective_lower.contains("refactor") {
            vec![
                PlannedTask::new("1-identify", "Identify code to refactor"),
                PlannedTask::new("2-plan", "Plan refactoring approach"),
                PlannedTask::new("3-execute", "Execute refactoring safely"),
                PlannedTask::new("4-verify", "Verify tests still pass"),
            ]
        } else if objective_lower.contains("fix") || objective_lower.contains("bug") {
            vec![
                PlannedTask::new("1-reproduce", "Reproduce the issue"),
                PlannedTask::new("2-analyze", "Analyze root cause"),
                PlannedTask::new("3-fix", "Implement fix"),
                PlannedTask::new("4-test", "Verify fix works"),
            ]
        } else if objective_lower.contains("feature") || objective_lower.contains("add") {
            vec![
                PlannedTask::new("1-spec", "Define feature specification"),
                PlannedTask::new("2-plan", "Plan implementation"),
                PlannedTask::new("3-implement", "Implement feature"),
                PlannedTask::new("4-document", "Update documentation"),
                PlannedTask::new("5-test", "Add tests"),
            ]
        } else {
            // Generic decomposition
            vec![
                PlannedTask::new("1-understand", "Understand the goal requirements"),
                PlannedTask::new("2-plan", "Create implementation plan"),
                PlannedTask::new("3-execute", "Execute the plan"),
                PlannedTask::new("4-verify", "Verify the results"),
            ]
        }
    }

    /// Summarize the approach for achieving the goal.
    fn summarize_approach(&self, objective: &str) -> String {
        let objective_lower = objective.to_lowercase();

        if objective_lower.contains("test") && objective_lower.contains("implement") {
            "Incremental implementation with test-driven development".to_string()
        } else if objective_lower.contains("refactor") {
            "Safe, incremental refactoring with test coverage".to_string()
        } else if objective_lower.contains("fix") || objective_lower.contains("bug") {
            "Root-cause analysis followed by targeted fix".to_string()
        } else if objective_lower.contains("feature") || objective_lower.contains("add") {
            "Feature-driven development with documentation".to_string()
        } else {
            "Goal-oriented execution with verification".to_string()
        }
    }

    /// Generate checkpoint list from planned tasks.
    pub fn to_checkpoints(&self, plan: &PlanResult) -> Vec<Checkpoint> {
        plan.tasks
            .iter()
            .map(|t| Checkpoint {
                id: t.id.clone(),
                description: t.description.clone(),
                completed: t.completed,
                created_at: chrono::Utc::now(),
                completed_at: None,
            })
            .collect()
    }
}

impl PlannedTask {
    /// Create a new task.
    pub fn new(id: impl Into<String>, description: impl Into<String>) -> Self {
        Self { id: id.into(), description: description.into(), completed: false }
    }

    /// Mark task as completed.
    pub fn complete(&mut self) {
        self.completed = true;
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_goal(objective: &str) -> GoalState {
        GoalState::new(
            uuid::Uuid::new_v4().to_string(),
            objective.to_string(),
            Some(10000),
        )
    }

    #[test]
    fn plan_feature_goal() {
        let planner = GoalPlanner::new();
        let goal = sample_goal("Add user authentication");
        let plan = planner.plan(&goal);

        assert!(!plan.tasks.is_empty());
        assert!(plan.approach.to_lowercase().contains("feature"));
        assert!(plan.tasks.iter().all(|t| !t.completed));
    }

    #[test]
    fn plan_bug_fix_goal() {
        let planner = GoalPlanner::new();
        let goal = sample_goal("Fix memory leak in cache");
        let plan = planner.plan(&goal);

        assert!(plan.tasks.iter().any(|t| t.id.contains("reproduce")));
        assert!(plan.tasks.iter().any(|t| t.id.contains("analyze")));
    }

    #[test]
    fn plan_refactor_goal() {
        let planner = GoalPlanner::new();
        let goal = sample_goal("Refactor database layer");
        let plan = planner.plan(&goal);

        assert!(plan.tasks.iter().any(|t| t.id.contains("identify")));
        assert!(plan.tasks.iter().any(|t| t.id.contains("execute")));
    }

    #[test]
    fn to_checkpoints_creates_checkpoints() {
        let planner = GoalPlanner::new();
        let goal = sample_goal("Test and implement feature");
        let plan = planner.plan(&goal);
        let checkpoints = planner.to_checkpoints(&plan);

        assert_eq!(checkpoints.len(), plan.tasks.len());
        assert!(checkpoints.iter().all(|c| !c.completed));
        assert!(checkpoints.iter().all(|c| c.completed_at.is_none()));
    }

    #[test]
    fn planned_task_complete() {
        let mut task = PlannedTask::new("1-test", "Write tests");
        assert!(!task.completed);
        task.complete();
        assert!(task.completed);
    }
}
