use crate::ModelInfo;

// OpenRouter models - split into multiple parts due to size

pub fn openrouter_a() -> Vec<ModelInfo> {
    vec![
        ModelInfo { id: "ai21/jamba-large-1.7".to_string(), name: "AI21: Jamba Large 1.7".to_string() },
        ModelInfo { id: "alibaba/tongyi-deepresearch-30b-a3b".to_string(), name: "Tongyi DeepResearch 30B A3B".to_string() },
        ModelInfo { id: "amazon/nova-2-lite-v1".to_string(), name: "Amazon: Nova 2 Lite".to_string() },
        ModelInfo { id: "amazon/nova-lite-v1".to_string(), name: "Amazon: Nova Lite 1.0".to_string() },
        ModelInfo { id: "amazon/nova-micro-v1".to_string(), name: "Amazon: Nova Micro 1.0".to_string() },
        ModelInfo { id: "amazon/nova-premier-v1".to_string(), name: "Amazon: Nova Premier 1.0".to_string() },
        ModelInfo { id: "amazon/nova-pro-v1".to_string(), name: "Amazon: Nova Pro 1.0".to_string() },
        ModelInfo { id: "anthropic/claude-3-haiku".to_string(), name: "Anthropic: Claude 3 Haiku".to_string() },
        ModelInfo { id: "anthropic/claude-3.5-haiku".to_string(), name: "Anthropic: Claude 3.5 Haiku".to_string() },
        ModelInfo { id: "anthropic/claude-haiku-4.5".to_string(), name: "Anthropic: Claude Haiku 4.5".to_string() },
        ModelInfo { id: "anthropic/claude-opus-4".to_string(), name: "Anthropic: Claude Opus 4".to_string() },
        ModelInfo { id: "anthropic/claude-opus-4.1".to_string(), name: "Anthropic: Claude Opus 4.1".to_string() },
        ModelInfo { id: "anthropic/claude-opus-4.5".to_string(), name: "Anthropic: Claude Opus 4.5".to_string() },
        ModelInfo { id: "anthropic/claude-opus-4.6".to_string(), name: "Anthropic: Claude Opus 4.6".to_string() },
        ModelInfo { id: "anthropic/claude-opus-4.6-fast".to_string(), name: "Anthropic: Claude Opus 4.6 (Fast)".to_string() },
        ModelInfo { id: "anthropic/claude-opus-4.7".to_string(), name: "Anthropic: Claude Opus 4.7".to_string() },
        ModelInfo { id: "anthropic/claude-opus-4.7-fast".to_string(), name: "Anthropic: Claude Opus 4.7 (Fast)".to_string() },
        ModelInfo { id: "anthropic/claude-sonnet-4".to_string(), name: "Anthropic: Claude Sonnet 4".to_string() },
        ModelInfo { id: "anthropic/claude-sonnet-4.5".to_string(), name: "Anthropic: Claude Sonnet 4.5".to_string() },
        ModelInfo { id: "anthropic/claude-sonnet-4.6".to_string(), name: "Anthropic: Claude Sonnet 4.6".to_string() },
        ModelInfo { id: "arcee-ai/trinity-large-thinking".to_string(), name: "Arcee AI: Trinity Large Thinking".to_string() },
        ModelInfo { id: "arcee-ai/trinity-large-thinking:free".to_string(), name: "Arcee AI: Trinity Large Thinking (free)".to_string() },
        ModelInfo { id: "arcee-ai/trinity-mini".to_string(), name: "Arcee AI: Trinity Mini".to_string() },
        ModelInfo { id: "arcee-ai/virtuoso-large".to_string(), name: "Arcee AI: Virtuoso Large".to_string() },
        ModelInfo { id: "auto".to_string(), name: "Auto".to_string() },
        ModelInfo { id: "baidu/cobuddy:free".to_string(), name: "Baidu Qianfan: CoBuddy (free)".to_string() },
        ModelInfo { id: "baidu/ernie-4.5-21b-a3b".to_string(), name: "Baidu: ERNIE 4.5 21B A3B".to_string() },
        ModelInfo { id: "baidu/ernie-4.5-vl-28b-a3b".to_string(), name: "Baidu: ERNIE 4.5 VL 28B A3B".to_string() },
        ModelInfo { id: "bytedance-seed/seed-1.6".to_string(), name: "ByteDance Seed: Seed 1.6".to_string() },
        ModelInfo { id: "bytedance-seed/seed-1.6-flash".to_string(), name: "ByteDance Seed: Seed 1.6 Flash".to_string() },
        ModelInfo { id: "bytedance-seed/seed-2.0-lite".to_string(), name: "ByteDance Seed: Seed-2.0-Lite".to_string() },
        ModelInfo { id: "bytedance-seed/seed-2.0-mini".to_string(), name: "ByteDance Seed: Seed-2.0-Mini".to_string() },
        ModelInfo { id: "cohere/command-r-08-2024".to_string(), name: "Cohere: Command R (08-2024)".to_string() },
        ModelInfo { id: "cohere/command-r-plus-08-2024".to_string(), name: "Cohere: Command R+ (08-2024)".to_string() },
        ModelInfo { id: "deepseek/deepseek-chat".to_string(), name: "DeepSeek: DeepSeek V3".to_string() },
        ModelInfo { id: "deepseek/deepseek-chat-v3-0324".to_string(), name: "DeepSeek: DeepSeek V3 0324".to_string() },
        ModelInfo { id: "deepseek/deepseek-chat-v3.1".to_string(), name: "DeepSeek: DeepSeek V3.1".to_string() },
        ModelInfo { id: "deepseek/deepseek-r1".to_string(), name: "DeepSeek: R1".to_string() },
        ModelInfo { id: "deepseek/deepseek-r1-0528".to_string(), name: "DeepSeek: R1 0528".to_string() },
        ModelInfo { id: "deepseek/deepseek-v3.1-terminus".to_string(), name: "DeepSeek: DeepSeek V3.1 Terminus".to_string() },
        ModelInfo { id: "deepseek/deepseek-v3.2".to_string(), name: "DeepSeek: DeepSeek V3.2".to_string() },
        ModelInfo { id: "deepseek/deepseek-v3.2-exp".to_string(), name: "DeepSeek: DeepSeek V3.2 Exp".to_string() },
        ModelInfo { id: "deepseek/deepseek-v4-flash".to_string(), name: "DeepSeek: DeepSeek V4 Flash".to_string() },
        ModelInfo { id: "deepseek/deepseek-v4-flash:free".to_string(), name: "DeepSeek: DeepSeek V4 Flash (free)".to_string() },
        ModelInfo { id: "deepseek/deepseek-v4-pro".to_string(), name: "DeepSeek: DeepSeek V4 Pro".to_string() },
        ModelInfo { id: "essentialai/rnj-1-instruct".to_string(), name: "EssentialAI: Rnj 1 Instruct".to_string() },
        ModelInfo { id: "google/gemini-2.0-flash-001".to_string(), name: "Google: Gemini 2.0 Flash".to_string() },
        ModelInfo { id: "google/gemini-2.0-flash-lite-001".to_string(), name: "Google: Gemini 2.0 Flash Lite".to_string() },
        ModelInfo { id: "google/gemini-2.5-flash".to_string(), name: "Google: Gemini 2.5 Flash".to_string() },
        ModelInfo { id: "google/gemini-2.5-flash-lite".to_string(), name: "Google: Gemini 2.5 Flash Lite".to_string() },
    ]
}

pub fn openrouter_b() -> Vec<ModelInfo> {
    vec![
        ModelInfo { id: "google/gemini-2.5-flash-lite-preview-09-2025".to_string(), name: "Google: Gemini 2.5 Flash Lite Preview 09-2025".to_string() },
        ModelInfo { id: "google/gemini-2.5-pro".to_string(), name: "Google: Gemini 2.5 Pro".to_string() },
        ModelInfo { id: "google/gemini-2.5-pro-preview".to_string(), name: "Google: Gemini 2.5 Pro Preview 06-05".to_string() },
        ModelInfo { id: "google/gemini-2.5-pro-preview-05-06".to_string(), name: "Google: Gemini 2.5 Pro Preview 05-06".to_string() },
        ModelInfo { id: "google/gemini-3-flash-preview".to_string(), name: "Google: Gemini 3 Flash Preview".to_string() },
        ModelInfo { id: "google/gemini-3.1-flash-lite".to_string(), name: "Google: Gemini 3.1 Flash Lite".to_string() },
        ModelInfo { id: "google/gemini-3.1-flash-lite-preview".to_string(), name: "Google: Gemini 3.1 Flash Lite Preview".to_string() },
        ModelInfo { id: "google/gemini-3.1-pro-preview".to_string(), name: "Google: Gemini 3.1 Pro Preview".to_string() },
        ModelInfo { id: "google/gemini-3.1-pro-preview-customtools".to_string(), name: "Google: Gemini 3.1 Pro Preview Custom Tools".to_string() },
        ModelInfo { id: "google/gemini-3.5-flash".to_string(), name: "Google: Gemini 3.5 Flash".to_string() },
        ModelInfo { id: "google/gemma-3-12b-it".to_string(), name: "Google: Gemma 3 12B".to_string() },
        ModelInfo { id: "google/gemma-3-27b-it".to_string(), name: "Google: Gemma 3 27B".to_string() },
        ModelInfo { id: "google/gemma-4-26b-a4b-it".to_string(), name: "Google: Gemma 4 26B A4B ".to_string() },
        ModelInfo { id: "google/gemma-4-26b-a4b-it:free".to_string(), name: "Google: Gemma 4 26B A4B  (free)".to_string() },
        ModelInfo { id: "google/gemma-4-31b-it".to_string(), name: "Google: Gemma 4 31B".to_string() },
        ModelInfo { id: "google/gemma-4-31b-it:free".to_string(), name: "Google: Gemma 4 31B (free)".to_string() },
        ModelInfo { id: "ibm-granite/granite-4.1-8b".to_string(), name: "IBM: Granite 4.1 8B".to_string() },
        ModelInfo { id: "inception/mercury-2".to_string(), name: "Inception: Mercury 2".to_string() },
        ModelInfo { id: "inclusionai/ling-2.6-1t".to_string(), name: "inclusionAI: Ling-2.6-1T".to_string() },
        ModelInfo { id: "inclusionai/ling-2.6-flash".to_string(), name: "inclusionAI: Ling-2.6-flash".to_string() },
        ModelInfo { id: "inclusionai/ring-2.6-1t".to_string(), name: "inclusionAI: Ring-2.6-1T".to_string() },
        ModelInfo { id: "kwaipilot/kat-coder-pro-v2".to_string(), name: "Kwaipilot: KAT-Coder-Pro V2".to_string() },
        ModelInfo { id: "meta-llama/llama-3.1-70b-instruct".to_string(), name: "Meta: Llama 3.1 70B Instruct".to_string() },
        ModelInfo { id: "meta-llama/llama-3.1-8b-instruct".to_string(), name: "Meta: Llama 3.1 8B Instruct".to_string() },
        ModelInfo { id: "meta-llama/llama-3.3-70b-instruct".to_string(), name: "Meta: Llama 3.3 70B Instruct".to_string() },
        ModelInfo { id: "meta-llama/llama-3.3-70b-instruct:free".to_string(), name: "Meta: Llama 3.3 70B Instruct (free)".to_string() },
        ModelInfo { id: "meta-llama/llama-4-scout".to_string(), name: "Meta: Llama 4 Scout".to_string() },
        ModelInfo { id: "minimax/minimax-m1".to_string(), name: "MiniMax: MiniMax M1".to_string() },
        ModelInfo { id: "minimax/minimax-m2".to_string(), name: "MiniMax: MiniMax M2".to_string() },
        ModelInfo { id: "minimax/minimax-m2.1".to_string(), name: "MiniMax: MiniMax M2.1".to_string() },
        ModelInfo { id: "minimax/minimax-m2.5".to_string(), name: "MiniMax: MiniMax M2.5".to_string() },
        ModelInfo { id: "minimax/minimax-m2.5:free".to_string(), name: "MiniMax: MiniMax M2.5 (free)".to_string() },
        ModelInfo { id: "minimax/minimax-m2.7".to_string(), name: "MiniMax: MiniMax M2.7".to_string() },
        ModelInfo { id: "mistralai/codestral-2508".to_string(), name: "Mistral: Codestral 2508".to_string() },
        ModelInfo { id: "mistralai/devstral-2512".to_string(), name: "Mistral: Devstral 2 2512".to_string() },
        ModelInfo { id: "mistralai/devstral-medium".to_string(), name: "Mistral: Devstral Medium".to_string() },
        ModelInfo { id: "mistralai/devstral-small".to_string(), name: "Mistral: Devstral Small 1.1".to_string() },
        ModelInfo { id: "mistralai/ministral-14b-2512".to_string(), name: "Mistral: Ministral 3 14B 2512".to_string() },
        ModelInfo { id: "mistralai/ministral-3b-2512".to_string(), name: "Mistral: Ministral 3 3B 2512".to_string() },
        ModelInfo { id: "mistralai/ministral-8b-2512".to_string(), name: "Mistral: Ministral 3 8B 2512".to_string() },
        ModelInfo { id: "mistralai/mistral-large".to_string(), name: "Mistral Large".to_string() },
        ModelInfo { id: "mistralai/mistral-large-2407".to_string(), name: "Mistral Large 2407".to_string() },
        ModelInfo { id: "mistralai/mistral-large-2411".to_string(), name: "Mistral: Mistral Large 3 2411".to_string() },
        ModelInfo { id: "mistralai/mistral-large-2512".to_string(), name: "Mistral: Mistral Large 3 2512".to_string() },
        ModelInfo { id: "mistralai/mistral-medium-3".to_string(), name: "Mistral: Mistral Medium 3".to_string() },
        ModelInfo { id: "mistralai/mistral-medium-3-5".to_string(), name: "Mistral: Mistral Medium 3.5".to_string() },
        ModelInfo { id: "mistralai/mistral-medium-3.1".to_string(), name: "Mistral: Mistral Medium 3.1".to_string() },
        ModelInfo { id: "mistralai/mistral-nemo".to_string(), name: "Mistral: Mistral Nemo".to_string() },
        ModelInfo { id: "mistralai/mistral-saba".to_string(), name: "Mistral: Saba".to_string() },
        ModelInfo { id: "mistralai/mistral-small-2603".to_string(), name: "Mistral: Mistral Small 4".to_string() },
        ModelInfo { id: "mistralai/mistral-small-3.2-24b-instruct".to_string(), name: "Mistral: Mistral Small 3.2 24B".to_string() },
    ]
}

pub fn openrouter_c() -> Vec<ModelInfo> {
    vec![
        ModelInfo { id: "mistralai/mixtral-8x22b-instruct".to_string(), name: "Mistral: Mixtral 8x22B Instruct".to_string() },
        ModelInfo { id: "mistralai/pixtral-large-2411".to_string(), name: "Mistral: Pixtral Large 2411".to_string() },
        ModelInfo { id: "mistralai/voxtral-small-24b-2507".to_string(), name: "Mistral: Voxtral Small 24B 2507".to_string() },
        ModelInfo { id: "moonshotai/kimi-k2".to_string(), name: "MoonshotAI: Kimi K2 0711".to_string() },
        ModelInfo { id: "moonshotai/kimi-k2-0905".to_string(), name: "MoonshotAI: Kimi K2 0905".to_string() },
        ModelInfo { id: "moonshotai/kimi-k2-thinking".to_string(), name: "MoonshotAI: Kimi K2 Thinking".to_string() },
        ModelInfo { id: "moonshotai/kimi-k2.5".to_string(), name: "MoonshotAI: Kimi K2.5".to_string() },
        ModelInfo { id: "moonshotai/kimi-k2.6".to_string(), name: "MoonshotAI: Kimi K2.6".to_string() },
        ModelInfo { id: "nex-agi/deepseek-v3.1-nex-n1".to_string(), name: "Nex AGI: DeepSeek V3.1 Nex N1".to_string() },
        ModelInfo { id: "nvidia/llama-3.3-nemotron-super-49b-v1.5".to_string(), name: "NVIDIA: Llama 3.3 Nemotron Super 49B V1.5".to_string() },
        ModelInfo { id: "nvidia/nemotron-3-nano-30b-a3b".to_string(), name: "NVIDIA: Nemotron 3 Nano 30B A3B".to_string() },
        ModelInfo { id: "nvidia/nemotron-3-nano-30b-a3b:free".to_string(), name: "NVIDIA: Nemotron 3 Nano 30B A3B (free)".to_string() },
        ModelInfo { id: "nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free".to_string(), name: "NVIDIA: Nemotron 3 Nano Omni (free)".to_string() },
        ModelInfo { id: "nvidia/nemotron-3-super-120b-a12b".to_string(), name: "NVIDIA: Nemotron 3 Super".to_string() },
        ModelInfo { id: "nvidia/nemotron-3-super-120b-a12b:free".to_string(), name: "NVIDIA: Nemotron 3 Super (free)".to_string() },
        ModelInfo { id: "nvidia/nemotron-nano-12b-v2-vl:free".to_string(), name: "NVIDIA: Nemotron Nano 12B 2 VL (free)".to_string() },
        ModelInfo { id: "nvidia/nemotron-nano-9b-v2".to_string(), name: "NVIDIA: Nemotron Nano 9B V2".to_string() },
        ModelInfo { id: "nvidia/nemotron-nano-9b-v2:free".to_string(), name: "NVIDIA: Nemotron Nano 9B V2 (free)".to_string() },
        ModelInfo { id: "openai/gpt-3.5-turbo".to_string(), name: "OpenAI: GPT-3.5 Turbo".to_string() },
        ModelInfo { id: "openai/gpt-3.5-turbo-0613".to_string(), name: "OpenAI: GPT-3.5 Turbo (older v0613)".to_string() },
        ModelInfo { id: "openai/gpt-3.5-turbo-16k".to_string(), name: "OpenAI: GPT-3.5 Turbo 16k".to_string() },
        ModelInfo { id: "openai/gpt-4".to_string(), name: "OpenAI: GPT-4".to_string() },
        ModelInfo { id: "openai/gpt-4-0314".to_string(), name: "OpenAI: GPT-4 (older v0314)".to_string() },
        ModelInfo { id: "openai/gpt-4-1106-preview".to_string(), name: "OpenAI: GPT-4 Turbo (older v1106)".to_string() },
        ModelInfo { id: "openai/gpt-4-turbo".to_string(), name: "OpenAI: GPT-4 Turbo".to_string() },
        ModelInfo { id: "openai/gpt-4-turbo-preview".to_string(), name: "OpenAI: GPT-4 Turbo Preview".to_string() },
        ModelInfo { id: "openai/gpt-4.1".to_string(), name: "OpenAI: GPT-4.1".to_string() },
        ModelInfo { id: "openai/gpt-4.1-mini".to_string(), name: "OpenAI: GPT-4.1 Mini".to_string() },
        ModelInfo { id: "openai/gpt-4.1-nano".to_string(), name: "OpenAI: GPT-4.1 Nano".to_string() },
        ModelInfo { id: "openai/gpt-4o".to_string(), name: "OpenAI: GPT-4o".to_string() },
        ModelInfo { id: "openai/gpt-4o-2024-05-13".to_string(), name: "OpenAI: GPT-4o (2024-05-13)".to_string() },
        ModelInfo { id: "openai/gpt-4o-2024-08-06".to_string(), name: "OpenAI: GPT-4o (2024-08-06)".to_string() },
        ModelInfo { id: "openai/gpt-4o-2024-11-20".to_string(), name: "OpenAI: GPT-4o (2024-11-20)".to_string() },
        ModelInfo { id: "openai/gpt-4o-audio-preview".to_string(), name: "OpenAI: GPT-4o Audio".to_string() },
        ModelInfo { id: "openai/gpt-4o-mini".to_string(), name: "OpenAI: GPT-4o-mini".to_string() },
        ModelInfo { id: "openai/gpt-4o-mini-2024-07-18".to_string(), name: "OpenAI: GPT-4o-mini (2024-07-18)".to_string() },
        ModelInfo { id: "openai/gpt-5".to_string(), name: "OpenAI: GPT-5".to_string() },
        ModelInfo { id: "openai/gpt-5-codex".to_string(), name: "OpenAI: GPT-5 Codex".to_string() },
        ModelInfo { id: "openai/gpt-5-mini".to_string(), name: "OpenAI: GPT-5 Mini".to_string() },
        ModelInfo { id: "openai/gpt-5-nano".to_string(), name: "OpenAI: GPT-5 Nano".to_string() },
        ModelInfo { id: "openai/gpt-5-pro".to_string(), name: "OpenAI: GPT-5 Pro".to_string() },
        ModelInfo { id: "openai/gpt-5.1".to_string(), name: "OpenAI: GPT-5.1".to_string() },
        ModelInfo { id: "openai/gpt-5.1-chat".to_string(), name: "OpenAI: GPT-5.1 Chat".to_string() },
        ModelInfo { id: "openai/gpt-5.1-codex".to_string(), name: "OpenAI: GPT-5.1-Codex".to_string() },
        ModelInfo { id: "openai/gpt-5.1-codex-max".to_string(), name: "OpenAI: GPT-5.1-Codex-Max".to_string() },
        ModelInfo { id: "openai/gpt-5.1-codex-mini".to_string(), name: "OpenAI: GPT-5.1-Codex-Mini".to_string() },
        ModelInfo { id: "openai/gpt-5.2".to_string(), name: "OpenAI: GPT-5.2".to_string() },
        ModelInfo { id: "openai/gpt-5.2-chat".to_string(), name: "OpenAI: GPT-5.2 Chat".to_string() },
        ModelInfo { id: "openai/gpt-5.2-codex".to_string(), name: "OpenAI: GPT-5.2-Codex".to_string() },
        ModelInfo { id: "openai/gpt-5.2-pro".to_string(), name: "OpenAI: GPT-5.2 Pro".to_string() },
    ]
}

pub fn openrouter_d() -> Vec<ModelInfo> {
    vec![
        ModelInfo { id: "openai/gpt-5.3-chat".to_string(), name: "OpenAI: GPT-5.3 Chat".to_string() },
        ModelInfo { id: "openai/gpt-5.3-codex".to_string(), name: "OpenAI: GPT-5.3-Codex".to_string() },
        ModelInfo { id: "openai/gpt-5.4".to_string(), name: "OpenAI: GPT-5.4".to_string() },
        ModelInfo { id: "openai/gpt-5.4-mini".to_string(), name: "OpenAI: GPT-5.4 Mini".to_string() },
        ModelInfo { id: "openai/gpt-5.4-nano".to_string(), name: "OpenAI: GPT-5.4 Nano".to_string() },
        ModelInfo { id: "openai/gpt-5.4-pro".to_string(), name: "OpenAI: GPT-5.4 Pro".to_string() },
        ModelInfo { id: "openai/gpt-5.5".to_string(), name: "OpenAI: GPT-5.5".to_string() },
        ModelInfo { id: "openai/gpt-5.5-pro".to_string(), name: "OpenAI: GPT-5.5 Pro".to_string() },
        ModelInfo { id: "openai/gpt-audio".to_string(), name: "OpenAI: GPT Audio".to_string() },
        ModelInfo { id: "openai/gpt-audio-mini".to_string(), name: "OpenAI: GPT Audio Mini".to_string() },
        ModelInfo { id: "openai/gpt-chat-latest".to_string(), name: "OpenAI: GPT Chat Latest".to_string() },
        ModelInfo { id: "openai/gpt-oss-120b".to_string(), name: "OpenAI: gpt-oss-120b".to_string() },
        ModelInfo { id: "openai/gpt-oss-120b:free".to_string(), name: "OpenAI: gpt-oss-120b (free)".to_string() },
        ModelInfo { id: "openai/gpt-oss-20b".to_string(), name: "OpenAI: gpt-oss-20b".to_string() },
        ModelInfo { id: "openai/gpt-oss-20b:free".to_string(), name: "OpenAI: gpt-oss-20b (free)".to_string() },
        ModelInfo { id: "openai/gpt-oss-safeguard-20b".to_string(), name: "OpenAI: gpt-oss-safeguard-20b".to_string() },
        ModelInfo { id: "openai/o1".to_string(), name: "OpenAI: o1".to_string() },
        ModelInfo { id: "openai/o3".to_string(), name: "OpenAI: o3".to_string() },
        ModelInfo { id: "openai/o3-deep-research".to_string(), name: "OpenAI: o3 Deep Research".to_string() },
        ModelInfo { id: "openai/o3-mini".to_string(), name: "OpenAI: o3 Mini".to_string() },
        ModelInfo { id: "openai/o3-mini-high".to_string(), name: "OpenAI: o3 Mini High".to_string() },
        ModelInfo { id: "openai/o3-pro".to_string(), name: "OpenAI: o3 Pro".to_string() },
        ModelInfo { id: "openai/o4-mini".to_string(), name: "OpenAI: o4 Mini".to_string() },
        ModelInfo { id: "openai/o4-mini-deep-research".to_string(), name: "OpenAI: o4 Mini Deep Research".to_string() },
        ModelInfo { id: "openai/o4-mini-high".to_string(), name: "OpenAI: o4 Mini High".to_string() },
        ModelInfo { id: "openrouter/auto".to_string(), name: "Auto Router".to_string() },
        ModelInfo { id: "openrouter/free".to_string(), name: "Free Models Router".to_string() },
        ModelInfo { id: "openrouter/owl-alpha".to_string(), name: "Owl Alpha".to_string() },
        ModelInfo { id: "poolside/laguna-m.1:free".to_string(), name: "Poolside: Laguna M.1 (free)".to_string() },
        ModelInfo { id: "poolside/laguna-xs.2:free".to_string(), name: "Poolside: Laguna XS.2 (free)".to_string() },
        ModelInfo { id: "prime-intellect/intellect-3".to_string(), name: "Prime Intellect: INTELLECT-3".to_string() },
        ModelInfo { id: "qwen/qwen-2.5-72b-instruct".to_string(), name: "Qwen2.5 72B Instruct".to_string() },
        ModelInfo { id: "qwen/qwen-2.5-7b-instruct".to_string(), name: "Qwen: Qwen2.5 7B Instruct".to_string() },
        ModelInfo { id: "qwen/qwen-plus".to_string(), name: "Qwen: Qwen-Plus".to_string() },
        ModelInfo { id: "qwen/qwen-plus-2025-07-28".to_string(), name: "Qwen: Qwen Plus 0728".to_string() },
        ModelInfo { id: "qwen/qwen-plus-2025-07-28:thinking".to_string(), name: "Qwen: Qwen Plus 0728 (thinking)".to_string() },
        ModelInfo { id: "qwen/qwen3-14b".to_string(), name: "Qwen: Qwen3 14B".to_string() },
        ModelInfo { id: "qwen/qwen3-235b-a22b".to_string(), name: "Qwen: Qwen3 235B A22B".to_string() },
        ModelInfo { id: "qwen/qwen3-235b-a22b-2507".to_string(), name: "Qwen: Qwen3 235B A22B Instruct 2507".to_string() },
        ModelInfo { id: "qwen/qwen3-235b-a22b-thinking-2507".to_string(), name: "Qwen: Qwen3 235B A22B Thinking 2507".to_string() },
        ModelInfo { id: "qwen/qwen3-30b-a3b".to_string(), name: "Qwen: Qwen3 30B A3B".to_string() },
        ModelInfo { id: "qwen/qwen3-30b-a3b-instruct-2507".to_string(), name: "Qwen: Qwen3 30B A3B Instruct 2507".to_string() },
        ModelInfo { id: "qwen/qwen3-30b-a3b-thinking-2507".to_string(), name: "Qwen: Qwen3 30B A3B Thinking 2507".to_string() },
        ModelInfo { id: "qwen/qwen3-32b".to_string(), name: "Qwen: Qwen3 32B".to_string() },
        ModelInfo { id: "qwen/qwen3-8b".to_string(), name: "Qwen: Qwen3 8B".to_string() },
        ModelInfo { id: "qwen/qwen3-coder".to_string(), name: "Qwen: Qwen3 Coder 480B A35B".to_string() },
        ModelInfo { id: "qwen/qwen3-coder-30b-a3b-instruct".to_string(), name: "Qwen: Qwen3 Coder 30B A3B Instruct".to_string() },
        ModelInfo { id: "qwen/qwen3-coder-flash".to_string(), name: "Qwen: Qwen3 Coder Flash".to_string() },
        ModelInfo { id: "qwen/qwen3-coder-next".to_string(), name: "Qwen: Qwen3 Coder Next".to_string() },
        ModelInfo { id: "qwen/qwen3-coder-plus".to_string(), name: "Qwen: Qwen3 Coder Plus".to_string() },
        ModelInfo { id: "qwen/qwen3-coder:free".to_string(), name: "Qwen: Qwen3 Coder 480B A35B (free)".to_string() },
    ]
}

pub fn openrouter_e() -> Vec<ModelInfo> {
    vec![
        ModelInfo { id: "qwen/qwen3-max".to_string(), name: "Qwen: Qwen3 Max".to_string() },
        ModelInfo { id: "qwen/qwen3-max-thinking".to_string(), name: "Qwen: Qwen3 Max Thinking".to_string() },
        ModelInfo { id: "qwen/qwen3-next-80b-a3b-instruct".to_string(), name: "Qwen: Qwen3 Next 80B A3B Instruct".to_string() },
        ModelInfo { id: "qwen/qwen3-next-80b-a3b-instruct:free".to_string(), name: "Qwen: Qwen3 Next 80B A3B Instruct (free)".to_string() },
        ModelInfo { id: "qwen/qwen3-next-80b-a3b-thinking".to_string(), name: "Qwen: Qwen3 Next 80B A3B Thinking".to_string() },
        ModelInfo { id: "qwen/qwen3-vl-235b-a22b-instruct".to_string(), name: "Qwen: Qwen3 VL 235B A22B Instruct".to_string() },
        ModelInfo { id: "qwen/qwen3-vl-235b-a22b-thinking".to_string(), name: "Qwen: Qwen3 VL 235B A22B Thinking".to_string() },
        ModelInfo { id: "qwen/qwen3-vl-30b-a3b-instruct".to_string(), name: "Qwen: Qwen3 VL 30B A3B Instruct".to_string() },
        ModelInfo { id: "qwen/qwen3-vl-30b-a3b-thinking".to_string(), name: "Qwen: Qwen3 VL 30B A3B Thinking".to_string() },
        ModelInfo { id: "qwen/qwen3-vl-32b-instruct".to_string(), name: "Qwen: Qwen3 VL 32B Instruct".to_string() },
        ModelInfo { id: "qwen/qwen3-vl-8b-instruct".to_string(), name: "Qwen: Qwen3 VL 8B Instruct".to_string() },
        ModelInfo { id: "qwen/qwen3-vl-8b-thinking".to_string(), name: "Qwen: Qwen3 VL 8B Thinking".to_string() },
        ModelInfo { id: "qwen/qwen3.5-122b-a10b".to_string(), name: "Qwen: Qwen3.5-122B-A10B".to_string() },
        ModelInfo { id: "qwen/qwen3.5-27b".to_string(), name: "Qwen: Qwen3.5-27B".to_string() },
        ModelInfo { id: "qwen/qwen3.5-35b-a3b".to_string(), name: "Qwen: Qwen3.5-35B-A3B".to_string() },
        ModelInfo { id: "qwen/qwen3.5-397b-a17b".to_string(), name: "Qwen: Qwen3.5 397B A17B".to_string() },
        ModelInfo { id: "qwen/qwen3.5-9b".to_string(), name: "Qwen: Qwen3.5-9B".to_string() },
        ModelInfo { id: "qwen/qwen3.5-flash-02-23".to_string(), name: "Qwen: Qwen3.5-Flash".to_string() },
        ModelInfo { id: "qwen/qwen3.5-plus-02-15".to_string(), name: "Qwen: Qwen3.5 Plus 2026-02-15".to_string() },
        ModelInfo { id: "qwen/qwen3.5-plus-20260420".to_string(), name: "Qwen: Qwen3.5 Plus 2026-04-20".to_string() },
        ModelInfo { id: "qwen/qwen3.6-27b".to_string(), name: "Qwen: Qwen3.6 27B".to_string() },
        ModelInfo { id: "qwen/qwen3.6-35b-a3b".to_string(), name: "Qwen: Qwen3.6 35B A3B".to_string() },
        ModelInfo { id: "qwen/qwen3.6-flash".to_string(), name: "Qwen: Qwen3.6 Flash".to_string() },
        ModelInfo { id: "qwen/qwen3.6-max-preview".to_string(), name: "Qwen: Qwen3.6 Max Preview".to_string() },
        ModelInfo { id: "qwen/qwen3.6-plus".to_string(), name: "Qwen: Qwen3.6 Plus".to_string() },
        ModelInfo { id: "qwen/qwen3.7-max".to_string(), name: "Qwen: Qwen3.7 Max".to_string() },
        ModelInfo { id: "rekaai/reka-edge".to_string(), name: "Reka Edge".to_string() },
        ModelInfo { id: "relace/relace-search".to_string(), name: "Relace: Relace Search".to_string() },
        ModelInfo { id: "sao10k/l3-euryale-70b".to_string(), name: "Sao10k: Llama 3 Euryale 70B v2.1".to_string() },
        ModelInfo { id: "sao10k/l3.1-euryale-70b".to_string(), name: "Sao10K: Llama 3.1 Euryale 70B v2.2".to_string() },
        ModelInfo { id: "stepfun/step-3.5-flash".to_string(), name: "StepFun: Step 3.5 Flash".to_string() },
        ModelInfo { id: "tencent/hy3-preview".to_string(), name: "Tencent: Hy3 preview".to_string() },
        ModelInfo { id: "thedrummer/rocinante-12b".to_string(), name: "TheDrummer: Rocinante 12B".to_string() },
        ModelInfo { id: "thedrummer/unslopnemo-12b".to_string(), name: "TheDrummer: UnslopNemo 12B".to_string() },
        ModelInfo { id: "upstage/solar-pro-3".to_string(), name: "Upstage: Solar Pro 3".to_string() },
        ModelInfo { id: "x-ai/grok-4.20".to_string(), name: "xAI: Grok 4.20".to_string() },
        ModelInfo { id: "x-ai/grok-4.3".to_string(), name: "xAI: Grok 4.3".to_string() },
        ModelInfo { id: "x-ai/grok-build-0.1".to_string(), name: "xAI: Grok Build 0.1".to_string() },
        ModelInfo { id: "xiaomi/mimo-v2-flash".to_string(), name: "Xiaomi: MiMo-V2-Flash".to_string() },
        ModelInfo { id: "xiaomi/mimo-v2-omni".to_string(), name: "Xiaomi: MiMo-V2-Omni".to_string() },
        ModelInfo { id: "xiaomi/mimo-v2-pro".to_string(), name: "Xiaomi: MiMo-V2-Pro".to_string() },
        ModelInfo { id: "xiaomi/mimo-v2.5".to_string(), name: "Xiaomi: MiMo-V2.5".to_string() },
        ModelInfo { id: "xiaomi/mimo-v2.5-pro".to_string(), name: "Xiaomi: MiMo-V2.5-Pro".to_string() },
        ModelInfo { id: "z-ai/glm-4-32b".to_string(), name: "Z.ai: GLM 4 32B ".to_string() },
        ModelInfo { id: "z-ai/glm-4.5".to_string(), name: "Z.ai: GLM 4.5".to_string() },
        ModelInfo { id: "z-ai/glm-4.5-air".to_string(), name: "Z.ai: GLM 4.5 Air".to_string() },
        ModelInfo { id: "z-ai/glm-4.5-air:free".to_string(), name: "Z.ai: GLM 4.5 Air (free)".to_string() },
        ModelInfo { id: "z-ai/glm-4.5v".to_string(), name: "Z.ai: GLM 4.5V".to_string() },
        ModelInfo { id: "z-ai/glm-4.6".to_string(), name: "Z.ai: GLM 4.6".to_string() },
        ModelInfo { id: "z-ai/glm-4.6v".to_string(), name: "Z.ai: GLM 4.6V".to_string() },
        ModelInfo { id: "z-ai/glm-4.7".to_string(), name: "Z.ai: GLM 4.7".to_string() },
        ModelInfo { id: "z-ai/glm-4.7-flash".to_string(), name: "Z.ai: GLM 4.7 Flash".to_string() },
        ModelInfo { id: "z-ai/glm-5".to_string(), name: "Z.ai: GLM 5".to_string() },
        ModelInfo { id: "z-ai/glm-5-turbo".to_string(), name: "Z.ai: GLM 5 Turbo".to_string() },
        ModelInfo { id: "z-ai/glm-5.1".to_string(), name: "Z.ai: GLM 5.1".to_string() },
        ModelInfo { id: "z-ai/glm-5v-turbo".to_string(), name: "Z.ai: GLM 5V Turbo".to_string() },
        ModelInfo { id: "~anthropic/claude-haiku-latest".to_string(), name: "Anthropic Claude Haiku Latest".to_string() },
        ModelInfo { id: "~anthropic/claude-opus-latest".to_string(), name: "Anthropic: Claude Opus Latest".to_string() },
        ModelInfo { id: "~anthropic/claude-sonnet-latest".to_string(), name: "Anthropic Claude Sonnet Latest".to_string() },
        ModelInfo { id: "~google/gemini-flash-latest".to_string(), name: "Google Gemini Flash Latest".to_string() },
        ModelInfo { id: "~google/gemini-pro-latest".to_string(), name: "Google Gemini Pro Latest".to_string() },
        ModelInfo { id: "~moonshotai/kimi-latest".to_string(), name: "MoonshotAI Kimi Latest".to_string() },
        ModelInfo { id: "~openai/gpt-latest".to_string(), name: "OpenAI GPT Latest".to_string() },
        ModelInfo { id: "~openai/gpt-mini-latest".to_string(), name: "OpenAI GPT Mini Latest".to_string() },
    ]
}

pub fn all_openrouter() -> Vec<ModelInfo> {
    let mut models = openrouter_a();
    models.extend(openrouter_b());
    models.extend(openrouter_c());
    models.extend(openrouter_d());
    models.extend(openrouter_e());
    models
}
