//! Keyword arrays for Python syntax highlighting.

pub const PYTHON_KEYWORDS: &[&str] = &[
    "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class", "continue",
    "def", "del", "elif", "else", "except", "finally", "for", "from", "global", "if", "import",
    "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return", "try", "while",
    "with", "yield", "match", "case",
];

pub const PYTHON_BUILTINS: &[&str] = &[
    "int",
    "float",
    "str",
    "bool",
    "list",
    "dict",
    "set",
    "tuple",
    "bytes",
    "bytearray",
    "range",
    "slice",
    "property",
    "classmethod",
    "staticmethod",
    "object",
    "type",
    "super",
    "vars",
    "dir",
    "hash",
    "len",
    "abs",
    "all",
    "any",
    "bin",
    "bool",
    "chr",
    "ord",
    "hex",
    "oct",
    "pow",
    "round",
    "sorted",
    "sum",
    "min",
    "max",
    "divmod",
    "enumerate",
    "filter",
    "map",
    "next",
    "reversed",
    "zip",
    "isinstance",
    "issubclass",
    "callable",
    "hasattr",
    "getattr",
    "setattr",
    "delattr",
    "repr",
    "ascii",
    "format",
    "print",
    "input",
    "open",
    "compile",
    "exec",
    "eval",
    "breakpoint",
    "exit",
    "quit",
    "help",
    "copyright",
    "credits",
    "license",
    "credits",
];

pub const PYTHON_FUNCTIONS: &[&str] = &[
    "print",
    "len",
    "range",
    "str",
    "int",
    "float",
    "list",
    "dict",
    "set",
    "tuple",
    "open",
    "input",
    "map",
    "filter",
    "zip",
    "enumerate",
    "sorted",
    "reversed",
    "sum",
    "min",
    "max",
    "abs",
    "any",
    "all",
    "isinstance",
    "hasattr",
    "getattr",
    "setattr",
    "repr",
    "format",
    "round",
    "pow",
    "divmod",
    "bin",
    "hex",
    "oct",
    "chr",
    "ord",
    "slice",
    "super",
    "type",
    "vars",
    "dir",
    "hash",
    "callable",
];

