pub mod overlay;
pub mod code_block;
pub mod collapsible;
pub mod agent_list;
pub mod top_bar;
pub mod message_list;
pub mod input_bar;
pub mod status_bar;
pub mod permission_modal;
pub mod command_palette;
pub mod context_panel;

pub use overlay::Overlay;
pub use code_block::{CodeBlock, CodeLine, LineStatus};
pub use collapsible::Collapsible;
pub use agent_list::{AgentList, AgentItem, AgentStatus};
pub use top_bar::TopBar;
pub use message_list::{MessageList, MessageItem};
pub use input_bar::{InputBar, InputMode};
pub use status_bar::StatusBar;
pub use permission_modal::{PermissionModal, PermissionAction};
pub use command_palette::{CommandPalette, PaletteItem, PaletteStep, PaletteCommand};
pub use context_panel::{ContextPanel, GitChange, GitStatus};