pub mod overlay;
pub mod model_picker;
pub mod onboarding;
pub mod code_block;
pub mod collapsible;
pub mod diff_viewer;
pub mod agent_list;
pub mod top_bar;
pub mod global_tags;
pub mod message_list;
pub mod input_bar;
pub mod status_bar;
pub mod permission_modal;
pub mod command_palette;
pub mod context_panel;
pub mod session_tree;
pub mod dialog_frame;
pub mod panel;
pub mod slash_menu;
pub mod shortcuts_panel;
pub mod settings_modal;
pub mod home_screen;
pub mod file_picker;
pub mod plan_modal;
pub mod context_usage_modal;
pub mod activity_panel;
pub mod extensions_modal;

#[cfg(test)]
mod top_bar_snapshots;

pub use overlay::Overlay;
pub use code_block::{CodeBlock, CodeLine, LineStatus};
pub use collapsible::Collapsible;
pub use diff_viewer::DiffViewer;
pub use agent_list::{AgentList, AgentItem, AgentStatus};
pub use top_bar::{TopBarViewModel, render_top_bar};
pub use global_tags::GlobalTagsViewModel;
pub use message_list::{MessageList, MessageItem};
pub use input_bar::{INPUT_PROMPT, input_bar_height};
pub use status_bar::StatusBar;
pub use permission_modal::{PermissionModal, PermissionAction};
pub use command_palette::{CommandPalette, PaletteCommand};
pub use context_panel::{ContextPanel, GitChange, GitStatus};
pub use session_tree::{SessionTreeNavigator, SessionTreeEntry};
pub use model_picker::{ModelPicker, ModelInfo, ProviderGroup};
pub use dialog_frame::DialogFrame;
pub use onboarding::Onboarding;
pub use slash_menu::{SlashMenu, SlashMenuItem, SLASH_COMMANDS};
pub use shortcuts_panel::{ShortcutsPanel, ShortcutDef, SHORTCUTS};
pub use settings_modal::{SettingsModal, THEMES};
pub use home_screen::{HomeScreen, HOME_MENU_ITEMS};
pub use file_picker::FilePicker;
pub use plan_modal::{PlanModal, PlanTool};
pub use context_usage_modal::{ContextUsageModal, render_context_usage_modal};
pub use activity_panel::{ActivityPanel, ACTIVITY_PANEL_WIDTH, render_activity_panel, should_show_activity_panel};
pub use extensions_modal::{ExtensionsModal, ExtensionTab, ExtensionItem, ExtensionScope, ExtensionAction, FilterScope};
