/// All built-in theme names available in Runie.
///
/// This is the canonical source. `runie_tui::theme::BUILTIN_THEMES` re-exports this
/// list so the public API stays consistent.
pub const BUILTIN_THEMES: &[&str] = &[
    "runie",
    "silkcircuit-neon",
    "silkcircuit-glow",
    "silkcircuit-soft",
    "silkcircuit-vibrant",
    "silkcircuit-dawn",
    "catppuccin-mocha",
    "catppuccin-macchiato",
    "catppuccin-frappe",
    "catppuccin-latte",
    "dracula",
    "nord",
    "gruvbox-dark",
    "gruvbox-light",
    "tokyo-night",
    "tokyo-night-storm",
    "tokyo-night-moon",
    "rose-pine",
    "rose-pine-moon",
    "rose-pine-dawn",
    "kanagawa-wave",
    "kanagawa-dragon",
    "kanagawa-lotus",
    "everforest-dark",
    "everforest-light",
    "ayu-dark",
    "ayu-light",
    "ayu-mirage",
    "one-dark",
    "one-light",
    "github-dark-dimmed",
    "github-light",
    "night-owl",
    "light-owl",
    "monokai-pro",
    "palenight",
    "solarized-dark",
    "solarized-light",
    "flexoki-dark",
    "flexoki-light",
];
